apiVersion: 1

datasources:
    - name: VictoriaMetrics
      type: prometheus
      access: proxy
      url: http://victoriametrics:8428
      isDefault: true

    - name: VictoriaMetrics - cluster
      type: prometheus
      access: proxy
      url: http://vmauth:8427/select/0/prometheus
      isDefault: false