include:
 - ../compose-base.yml
services:
  fluentd:
    build: .
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ${PWD}/fluent.conf:/fluentd/etc/fluent.conf
    depends_on: [victorialogs]
    ports:
      - "5140:5140"
      - "24224:24224"
    healthcheck:
      test: ["CMD", "nc", "-z", "-n", "-v", "127.0.0.1", "24224"]
      start_period: 3s
  nginx:
    image: nginx:1.27
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      start_period: 3s
    ports:
      - "8080:80"
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        labels: com.docker.compose.service
    depends_on:
      fluentd:
        condition: service_healthy
