exporters:
  elasticsearch:
    endpoints:
      - http://collector-ha-elasticsearch-victorialogs-1:9428/insert/elasticsearch
      - http://collector-ha-elasticsearch-victorialogs-2:9428/insert/elasticsearch
receivers:
  filelog:
    include: [/var/lib/docker/containers/**/*.log]
    resource:
      region: us-east-1
service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [elasticsearch]
