# File contains default list of alerts for vmbackupmanager.
# The alerts below are just recommendations and may require some updates
# and threshold calibration according to every specific setup.
groups:
  - name: vmbackupmanager
    rules:
      - alert: NoLatestBackupWithinLastDay
        expr: |
          (
            vm_backup_last_success_at{type="latest"} == 0
            and on(job, instance)
            vm_app_uptime_seconds > 24 * 3600
          )
          or
          (
            vm_backup_last_success_at{type="latest"} > 0
            and time() - vm_backup_last_success_at{type="latest"} > 24 * 3600
          )
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "latest backup hasn't completed successfully for more than 1 day on \"{{ $labels.job }}\"(\"{{ $labels.instance }}\")"
          description: >
            vmbackupmanager on "{{ $labels.job }}"("{{ $labels.instance }}") hasn't completed the latest backup for more than 1 day.
            Check error logs on vmbackupmanager for root cause.

      - alert: NoHourlyBackupWithinLastDay
        expr: |
          (
            vm_backup_last_success_at{type="hourly"} == 0
            and on(job, instance)
            vm_app_uptime_seconds > 24 * 3600
          )
          or
          (
            vm_backup_last_success_at{type="hourly"} > 0
            and time() - vm_backup_last_success_at{type="hourly"} > 24 * 3600
          )
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "hourly backup hasn't completed successfully for more than 1 day on \"{{ $labels.job }}\"(\"{{ $labels.instance }}\")"
          description: >
            vmbackupmanager on "{{ $labels.job }}"("{{ $labels.instance }}") hasn't completed an hourly backup for more than 1 day.
            Check error logs on vmbackupmanager for root cause.

      - alert: NoDailyBackupWithinLast3Days
        expr: |
          (
            vm_backup_last_success_at{type="daily"} == 0
            and on(job, instance)
            vm_app_uptime_seconds > 3 * 24 * 3600
          )
          or
          (
            vm_backup_last_success_at{type="daily"} > 0
            and time() - vm_backup_last_success_at{type="daily"} > 3 * 24 * 3600
          )
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "daily backup hasn't completed successfully for more than 3 days on \"{{ $labels.job }}\"(\"{{ $labels.instance }}\")"
          description: >
            vmbackupmanager on "{{ $labels.job }}"("{{ $labels.instance }}") hasn't completed a daily backup for more than 3 days.
            Check error logs on vmbackupmanager for root cause.

      - alert: NoWeeklyBackupWithinLast14Days
        expr: |
          (
            vm_backup_last_success_at{type="weekly"} == 0
            and on(job, instance)
            vm_app_uptime_seconds > 14 * 24 * 3600
          )
          or
          (
            vm_backup_last_success_at{type="weekly"} > 0
            and time() - vm_backup_last_success_at{type="weekly"} > 14 * 24 * 3600
          )
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "weekly backup hasn't completed successfully for more than 14 days on \"{{ $labels.job }}\"(\"{{ $labels.instance }}\")"
          description: >
            vmbackupmanager on "{{ $labels.job }}"("{{ $labels.instance }}") hasn't completed a weekly backup for more than 14 days.
            Check error logs on vmbackupmanager for root cause.

      - alert: NoMonthlyBackupWithinLast62Days
        expr: |
          (
            vm_backup_last_success_at{type="monthly"} == 0
            and on(job, instance)
            vm_app_uptime_seconds > 62 * 24 * 3600
          )
          or
          (
            vm_backup_last_success_at{type="monthly"} > 0
            and time() - vm_backup_last_success_at{type="monthly"} > 62 * 24 * 3600
          )
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "monthly backup hasn't completed successfully for more than 62 days on \"{{ $labels.job }}\"(\"{{ $labels.instance }}\")"
          description: >
            vmbackupmanager on "{{ $labels.job }}"("{{ $labels.instance }}") hasn't completed a monthly backup for more than 62 days.
            Check error logs on vmbackupmanager for root cause.
