apiVersion: 1

datasources:
  - name: VictoriaTraces
    type: jaeger
    access: proxy
    url:  http://vmauth:8427/select/jaeger/

  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://vmauth:8427/
