version: "2"
linters:
  enable:
    - errorlint
  settings:
    errcheck:
      exclude-functions:
        - (net/http.ResponseWriter).Write
    errorlint:
      errorf: true
      comparison: false
      asserts: false
  exclusions:
    generated: lax
    presets:
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: 'SA(4003|1019|5011):'
    paths:
      - ^app/vmui/
