run:
  timeout: 2m

enable:
  - revive

issues:
  exclude-rules:
    - linters:
      - staticcheck
      text: "SA(4003|1019|5011):"

linters-settings:
  errcheck:
    exclude: ./errcheck_excludes.txt
