version: "2"
linters:
  settings:
    errcheck:
      exclude-functions:
        - (net/http.ResponseWriter).Write
  exclusions:
    generated: lax
    presets:
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: 'SA(4003|1019|5011):'
    paths:
      - ^app/vmui/
