api:
  enabled: true
  address: 0.0.0.0:8686
sources:
  docker:
    type: docker_logs
  metrics:
    type: internal_metrics
transforms:
  parser:
    type: remap
    inputs:
      - docker
    source: |
      message, err = parse_json(.message) 
      if (err == null) {
        if exists(message.msg) {
          message = message.msg
        } else if exists(message.message) {
          message = message.message
        } else {
          message = message
        }
      } else {
        message = .message
      }
      .message = message
sinks:
  loki:
    type: loki
    inputs:
      - parser
    endpoint: http://victorialogs:9428/insert/loki/
    compression: gzip
    path: /api/v1/push?_msg_field=message.msg&_time_field=timestamp&_stream_fields=com_docker_compose_service
    labels:
      "*": "{{ label }}"
    encoding:
      codec: raw_message
  victoriametrics:
    type: prometheus_remote_write
    endpoint: http://victoriametrics:8428/api/v1/write
    inputs: 
      - metrics
    healthcheck:
      enabled: false
