// Code generated by qtc from "web.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line app/vmalert/web.qtpl:1
package main

//line app/vmalert/web.qtpl:3
import (
	"net/http"
	"sort"
	"time"

	"github.com/VictoriaMetrics/VictoriaMetrics/app/vmalert/notifier"
	"github.com/VictoriaMetrics/VictoriaMetrics/app/vmalert/rule"
	"github.com/VictoriaMetrics/VictoriaMetrics/app/vmalert/tpl"
	"github.com/VictoriaMetrics/VictoriaMetrics/app/vmalert/vmalertutil"
)

//line app/vmalert/web.qtpl:14
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line app/vmalert/web.qtpl:14
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line app/vmalert/web.qtpl:14
func StreamControls(qw422016 *qt422016.Writer, prefix, currentIcon, currentText string, icons, filters map[string]string, search bool) {
//line app/vmalert/web.qtpl:14
	qw422016.N().S(`
    <div class="btn-toolbar mb-3" role="toolbar">
        <div class="d-flex gap-2 justify-content-between w-100">
            <div class="d-flex gap-2 align-items-center">
                <a class="btn btn-outline-dark d-flex align-items-center" role="button" onclick="actionAll(true)">
                    <span class="d-none d-md-block">Collapse All</span>
                    <svg class="d-md-none" height="20" width="20">
                        <use href="`)
//line app/vmalert/web.qtpl:21
	qw422016.E().S(prefix)
//line app/vmalert/web.qtpl:21
	qw422016.N().S(`static/icons/icons.svg#collapse"/>
                    </svg>
                </a>
                <a class="btn btn-outline-dark d-flex align-items-center" role="button" onclick="actionAll(false)">
                    <span class="d-none d-md-block">Expand All</span>
                    <svg class="d-md-none" width="20" height="20">
                        <use href="`)
//line app/vmalert/web.qtpl:27
	qw422016.E().S(prefix)
//line app/vmalert/web.qtpl:27
	qw422016.N().S(`static/icons/icons.svg#expand"/>
                    </svg>
                </a>
                `)
//line app/vmalert/web.qtpl:30
	if len(filters) > 0 {
//line app/vmalert/web.qtpl:30
		qw422016.N().S(`
                    <span class="d-none d-md-inline-block">Filter by status:</span>
                    <svg class="d-md-none" width="20" height="20">
                        <use href="`)
//line app/vmalert/web.qtpl:33
		qw422016.E().S(prefix)
//line app/vmalert/web.qtpl:33
		qw422016.N().S(`static/icons/icons.svg#filter">
                    </svg>
                    <div class="dropdown">
                        <button
                            class="btn btn-outline-dark dropdown-toggle d-flex justify-content-between align-items-center"
                            type="button"
                            data-bs-toggle="dropdown"
                            aria-expanded="false"
                        >
                            <span class="d-none d-md-inline-block">`)
//line app/vmalert/web.qtpl:42
		qw422016.E().S(currentText)
//line app/vmalert/web.qtpl:42
		qw422016.N().S(`</span>
                            <svg class="d-md-none" width="22" height="22">
                                <use href="`)
//line app/vmalert/web.qtpl:44
		qw422016.E().S(prefix)
//line app/vmalert/web.qtpl:44
		qw422016.N().S(`static/icons/icons.svg#`)
//line app/vmalert/web.qtpl:44
		qw422016.E().S(currentIcon)
//line app/vmalert/web.qtpl:44
		qw422016.N().S(`"/>
                            </svg>
                        </button>
                        <ul class="dropdown-menu">
                            `)
//line app/vmalert/web.qtpl:48
		for key, title := range filters {
//line app/vmalert/web.qtpl:48
			qw422016.N().S(`
                                `)
//line app/vmalert/web.qtpl:49
			if title != currentText {
//line app/vmalert/web.qtpl:49
				qw422016.N().S(`
                                    <li>
                                        <a class="dropdown-item" onclick="groupFilter('`)
//line app/vmalert/web.qtpl:51
				qw422016.E().S(key)
//line app/vmalert/web.qtpl:51
				qw422016.N().S(`')">
                                            <span class="d-none d-md-inline-block">`)
//line app/vmalert/web.qtpl:52
				qw422016.E().S(title)
//line app/vmalert/web.qtpl:52
				qw422016.N().S(`</span>
                                            <svg class="d-md-none" width="22" height="22">
                                                <use href="`)
//line app/vmalert/web.qtpl:54
				qw422016.E().S(prefix)
//line app/vmalert/web.qtpl:54
				qw422016.N().S(`static/icons/icons.svg#`)
//line app/vmalert/web.qtpl:54
				qw422016.E().S(icons[key])
//line app/vmalert/web.qtpl:54
				qw422016.N().S(`"/>
                                            </svg>
                                        </a>
                                    </li>
                                `)
//line app/vmalert/web.qtpl:58
			}
//line app/vmalert/web.qtpl:58
			qw422016.N().S(`
                            `)
//line app/vmalert/web.qtpl:59
		}
//line app/vmalert/web.qtpl:59
		qw422016.N().S(`
                        </ul>
                    </div>
                `)
//line app/vmalert/web.qtpl:62
	}
//line app/vmalert/web.qtpl:62
	qw422016.N().S(`
            </div>
            `)
//line app/vmalert/web.qtpl:64
	if search {
//line app/vmalert/web.qtpl:64
		qw422016.N().S(`
                <div class="input-group flex-grow-1 justify-content-end">
                    <span class="input-group-text">
                        <svg height="25" width="20">
                            <use href="`)
//line app/vmalert/web.qtpl:68
		qw422016.E().S(prefix)
//line app/vmalert/web.qtpl:68
		qw422016.N().S(`static/icons/icons.svg#search">
                        </svg>
                    </span>
                    <input id="search" placeholder="Filter by group, rule or labels" type="text" class="form-control"/>
                </div>
            `)
//line app/vmalert/web.qtpl:73
	}
//line app/vmalert/web.qtpl:73
	qw422016.N().S(`
        </div>
    </div>
    <div class="progress">
        <div class="spinner-grow" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
        <div class="spinner-grow" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
        <div class="spinner-grow" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>
`)
//line app/vmalert/web.qtpl:87
}

//line app/vmalert/web.qtpl:87
func WriteControls(qq422016 qtio422016.Writer, prefix, currentIcon, currentText string, icons, filters map[string]string, search bool) {
//line app/vmalert/web.qtpl:87
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vmalert/web.qtpl:87
	StreamControls(qw422016, prefix, currentIcon, currentText, icons, filters, search)
//line app/vmalert/web.qtpl:87
	qt422016.ReleaseWriter(qw422016)
//line app/vmalert/web.qtpl:87
}

//line app/vmalert/web.qtpl:87
func Controls(prefix, currentIcon, currentText string, icons, filters map[string]string, search bool) string {
//line app/vmalert/web.qtpl:87
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vmalert/web.qtpl:87
	WriteControls(qb422016, prefix, currentIcon, currentText, icons, filters, search)
//line app/vmalert/web.qtpl:87
	qs422016 := string(qb422016.B)
//line app/vmalert/web.qtpl:87
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vmalert/web.qtpl:87
	return qs422016
//line app/vmalert/web.qtpl:87
}

//line app/vmalert/web.qtpl:89
func StreamWelcome(qw422016 *qt422016.Writer, r *http.Request) {
//line app/vmalert/web.qtpl:89
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:90
	tpl.StreamHeader(qw422016, r, navItems, "vmalert", getLastConfigError())
//line app/vmalert/web.qtpl:90
	qw422016.N().S(`
    <p>
        API:<br>
        `)
//line app/vmalert/web.qtpl:93
	for _, p := range apiLinks {
//line app/vmalert/web.qtpl:93
		qw422016.N().S(`
            `)
//line app/vmalert/web.qtpl:94
		p, doc := p[0], p[1]

//line app/vmalert/web.qtpl:94
		qw422016.N().S(`
            <a href="`)
//line app/vmalert/web.qtpl:95
		qw422016.E().S(p)
//line app/vmalert/web.qtpl:95
		qw422016.N().S(`">`)
//line app/vmalert/web.qtpl:95
		qw422016.E().S(p)
//line app/vmalert/web.qtpl:95
		qw422016.N().S(`</a> - `)
//line app/vmalert/web.qtpl:95
		qw422016.E().S(doc)
//line app/vmalert/web.qtpl:95
		qw422016.N().S(`<br/>
        `)
//line app/vmalert/web.qtpl:96
	}
//line app/vmalert/web.qtpl:96
	qw422016.N().S(`
        `)
//line app/vmalert/web.qtpl:97
	if r.Header.Get("X-Forwarded-For") == "" {
//line app/vmalert/web.qtpl:97
		qw422016.N().S(`
            System:<br>
            `)
//line app/vmalert/web.qtpl:99
		for _, p := range systemLinks {
//line app/vmalert/web.qtpl:99
			qw422016.N().S(`
                `)
//line app/vmalert/web.qtpl:100
			p, doc := p[0], p[1]

//line app/vmalert/web.qtpl:100
			qw422016.N().S(`
                <a href="`)
//line app/vmalert/web.qtpl:101
			qw422016.E().S(p)
//line app/vmalert/web.qtpl:101
			qw422016.N().S(`">`)
//line app/vmalert/web.qtpl:101
			qw422016.E().S(p)
//line app/vmalert/web.qtpl:101
			qw422016.N().S(`</a> - `)
//line app/vmalert/web.qtpl:101
			qw422016.E().S(doc)
//line app/vmalert/web.qtpl:101
			qw422016.N().S(`<br/>
            `)
//line app/vmalert/web.qtpl:102
		}
//line app/vmalert/web.qtpl:102
		qw422016.N().S(`
        `)
//line app/vmalert/web.qtpl:103
	}
//line app/vmalert/web.qtpl:103
	qw422016.N().S(`
    </p>
    `)
//line app/vmalert/web.qtpl:105
	tpl.StreamFooter(qw422016, r)
//line app/vmalert/web.qtpl:105
	qw422016.N().S(`
`)
//line app/vmalert/web.qtpl:106
}

//line app/vmalert/web.qtpl:106
func WriteWelcome(qq422016 qtio422016.Writer, r *http.Request) {
//line app/vmalert/web.qtpl:106
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vmalert/web.qtpl:106
	StreamWelcome(qw422016, r)
//line app/vmalert/web.qtpl:106
	qt422016.ReleaseWriter(qw422016)
//line app/vmalert/web.qtpl:106
}

//line app/vmalert/web.qtpl:106
func Welcome(r *http.Request) string {
//line app/vmalert/web.qtpl:106
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vmalert/web.qtpl:106
	WriteWelcome(qb422016, r)
//line app/vmalert/web.qtpl:106
	qs422016 := string(qb422016.B)
//line app/vmalert/web.qtpl:106
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vmalert/web.qtpl:106
	return qs422016
//line app/vmalert/web.qtpl:106
}

//line app/vmalert/web.qtpl:108
func StreamListGroups(qw422016 *qt422016.Writer, r *http.Request, groups []*rule.ApiGroup, filter string) {
//line app/vmalert/web.qtpl:108
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:110
	prefix := vmalertutil.Prefix(r.URL.Path)
	filters := map[string]string{
		"":          "All",
		"unhealthy": "Unhealthy",
		"nomatch":   "No Match",
	}
	icons := map[string]string{
		"":          "all",
		"unhealthy": "unhealthy",
		"nomatch":   "nomatch",
	}
	currentText := filters[filter]
	currentIcon := icons[filter]

//line app/vmalert/web.qtpl:123
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:124
	tpl.StreamHeader(qw422016, r, navItems, "Groups", getLastConfigError())
//line app/vmalert/web.qtpl:124
	qw422016.N().S(`
        `)
//line app/vmalert/web.qtpl:125
	StreamControls(qw422016, prefix, currentIcon, currentText, icons, filters, true)
//line app/vmalert/web.qtpl:125
	qw422016.N().S(`
        `)
//line app/vmalert/web.qtpl:126
	if len(groups) > 0 {
//line app/vmalert/web.qtpl:126
		qw422016.N().S(`
            `)
//line app/vmalert/web.qtpl:127
		for _, g := range groups {
//line app/vmalert/web.qtpl:127
			qw422016.N().S(`
                <div id="group-`)
//line app/vmalert/web.qtpl:128
			qw422016.E().S(g.ID)
//line app/vmalert/web.qtpl:128
			qw422016.N().S(`" class="w-100 border-0 flex-column vm-group`)
//line app/vmalert/web.qtpl:128
			if g.Unhealthy > 0 {
//line app/vmalert/web.qtpl:128
				qw422016.N().S(` alert-danger`)
//line app/vmalert/web.qtpl:128
			}
//line app/vmalert/web.qtpl:128
			qw422016.N().S(`">
                    <span class="d-flex justify-content-between">
                        <a
                            class="vm-group-search"
                            href="#group-`)
//line app/vmalert/web.qtpl:132
			qw422016.E().S(g.ID)
//line app/vmalert/web.qtpl:132
			qw422016.N().S(`"
                        >`)
//line app/vmalert/web.qtpl:133
			qw422016.E().S(g.Name)
//line app/vmalert/web.qtpl:133
			if g.Type != "prometheus" {
//line app/vmalert/web.qtpl:133
				qw422016.N().S(` (`)
//line app/vmalert/web.qtpl:133
				qw422016.E().S(g.Type)
//line app/vmalert/web.qtpl:133
				qw422016.N().S(`)`)
//line app/vmalert/web.qtpl:133
			}
//line app/vmalert/web.qtpl:133
			qw422016.N().S(` (every `)
//line app/vmalert/web.qtpl:133
			qw422016.N().FPrec(g.Interval, 0)
//line app/vmalert/web.qtpl:133
			qw422016.N().S(`s) #</a>
                        <span
                            class="flex-grow-1 d-flex justify-content-end"
                            role="button"
                            data-bs-toggle="collapse"
                            data-bs-target="#item-`)
//line app/vmalert/web.qtpl:138
			qw422016.E().S(g.ID)
//line app/vmalert/web.qtpl:138
			qw422016.N().S(`"
                        >
                            <span class="d-flex gap-2">
                                `)
//line app/vmalert/web.qtpl:141
			if g.Unhealthy > 0 {
//line app/vmalert/web.qtpl:141
				qw422016.N().S(`<span class="badge bg-danger" title="Number of rules with status Error">`)
//line app/vmalert/web.qtpl:141
				qw422016.N().D(g.Unhealthy)
//line app/vmalert/web.qtpl:141
				qw422016.N().S(`</span> `)
//line app/vmalert/web.qtpl:141
			}
//line app/vmalert/web.qtpl:141
			qw422016.N().S(`
                                `)
//line app/vmalert/web.qtpl:142
			if g.NoMatch > 0 {
//line app/vmalert/web.qtpl:142
				qw422016.N().S(`<span class="badge bg-warning" title="Number of rules with status NoMatch">`)
//line app/vmalert/web.qtpl:142
				qw422016.N().D(g.NoMatch)
//line app/vmalert/web.qtpl:142
				qw422016.N().S(`</span> `)
//line app/vmalert/web.qtpl:142
			}
//line app/vmalert/web.qtpl:142
			qw422016.N().S(`
                                <span class="badge bg-success" title="Number of rules with status Ok">`)
//line app/vmalert/web.qtpl:143
			qw422016.N().D(g.Healthy)
//line app/vmalert/web.qtpl:143
			qw422016.N().S(`</span>
                            </span>
                        </span>
                    </span>
                    <span
                        class="d-flex flex-column row-gap-2 mb-2"
                        role="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#item-`)
//line app/vmalert/web.qtpl:151
			qw422016.E().S(g.ID)
//line app/vmalert/web.qtpl:151
			qw422016.N().S(`"
                    >
                        <span class="fs-6 text-start vm-group-search w-100 fw-lighter">`)
//line app/vmalert/web.qtpl:153
			qw422016.E().S(g.File)
//line app/vmalert/web.qtpl:153
			qw422016.N().S(`</span>
                        `)
//line app/vmalert/web.qtpl:154
			if len(g.Params) > 0 {
//line app/vmalert/web.qtpl:154
				qw422016.N().S(`
                            <span class="fs-6 text-start w-100 d-flex justify-content-between fw-lighter">
                                <span>Extra params</span>
                                <span class="d-flex align-items-center gap-2">
                                    `)
//line app/vmalert/web.qtpl:158
				for _, param := range g.Params {
//line app/vmalert/web.qtpl:158
					qw422016.N().S(`
                                        <span class="badge bg-primary">`)
//line app/vmalert/web.qtpl:159
					qw422016.E().S(param)
//line app/vmalert/web.qtpl:159
					qw422016.N().S(`</span>
                                    `)
//line app/vmalert/web.qtpl:160
				}
//line app/vmalert/web.qtpl:160
				qw422016.N().S(`
                                </span>
                            </span>
                        `)
//line app/vmalert/web.qtpl:163
			}
//line app/vmalert/web.qtpl:163
			qw422016.N().S(`
                        `)
//line app/vmalert/web.qtpl:164
			if len(g.Headers) > 0 {
//line app/vmalert/web.qtpl:164
				qw422016.N().S(`
                            <span class="fs-6 text-start w-100 d-flex justify-content-between fw-lighter">
                                <span>Extra headers</span>
                                <span class="d-flex align-items-center gap-2">
                                    `)
//line app/vmalert/web.qtpl:168
				for _, header := range g.Headers {
//line app/vmalert/web.qtpl:168
					qw422016.N().S(`
                                        <span class="badge bg-primary label">`)
//line app/vmalert/web.qtpl:169
					qw422016.E().S(header)
//line app/vmalert/web.qtpl:169
					qw422016.N().S(`</span>
                                    `)
//line app/vmalert/web.qtpl:170
				}
//line app/vmalert/web.qtpl:170
				qw422016.N().S(`
                                </span>
                            </span>
                        `)
//line app/vmalert/web.qtpl:173
			}
//line app/vmalert/web.qtpl:173
			qw422016.N().S(`
                    </span>
                    <div class="collapse" id="item-`)
//line app/vmalert/web.qtpl:175
			qw422016.E().S(g.ID)
//line app/vmalert/web.qtpl:175
			qw422016.N().S(`">
                        <table class="table table-striped table-hover table-sm">
                            <thead>
                                <tr>
                                    <th scope="col" class="w-50">Rule</th>
                                    <th scope="col" class="w-20 text-center" title="How many series were produced by the rule">Series</th>
                                    <th scope="col" class="w-20 text-center" title="How many seconds ago rule was executed">Updated</th>
                                    <th scope="col" class="w-10"></th>
                                </tr>
                            </thead>
                            <tbody>
                                `)
//line app/vmalert/web.qtpl:186
			for _, r := range g.Rules {
//line app/vmalert/web.qtpl:186
				qw422016.N().S(`
                                    <tr class="vm-item`)
//line app/vmalert/web.qtpl:187
				if r.LastError != "" {
//line app/vmalert/web.qtpl:187
					qw422016.N().S(` alert-danger`)
//line app/vmalert/web.qtpl:187
				}
//line app/vmalert/web.qtpl:187
				qw422016.N().S(`">
                                        <td>
                                            <div class="row">
                                                <div class="col-12 mb-2">
                                                    `)
//line app/vmalert/web.qtpl:191
				if r.Type == "alerting" {
//line app/vmalert/web.qtpl:191
					qw422016.N().S(`
                                                        `)
//line app/vmalert/web.qtpl:192
					if r.KeepFiringFor > 0 {
//line app/vmalert/web.qtpl:192
						qw422016.N().S(`
                                                            <b>alert:</b> `)
//line app/vmalert/web.qtpl:193
						qw422016.E().S(r.Name)
//line app/vmalert/web.qtpl:193
						qw422016.N().S(` (for: `)
//line app/vmalert/web.qtpl:193
						qw422016.E().V(r.Duration)
//line app/vmalert/web.qtpl:193
						qw422016.N().S(` seconds, keep_firing_for: `)
//line app/vmalert/web.qtpl:193
						qw422016.E().V(r.KeepFiringFor)
//line app/vmalert/web.qtpl:193
						qw422016.N().S(` seconds)
                                                        `)
//line app/vmalert/web.qtpl:194
					} else {
//line app/vmalert/web.qtpl:194
						qw422016.N().S(`
                                                            <b>alert:</b> `)
//line app/vmalert/web.qtpl:195
						qw422016.E().S(r.Name)
//line app/vmalert/web.qtpl:195
						qw422016.N().S(` (for: `)
//line app/vmalert/web.qtpl:195
						qw422016.E().V(r.Duration)
//line app/vmalert/web.qtpl:195
						qw422016.N().S(` seconds)
                                                        `)
//line app/vmalert/web.qtpl:196
					}
//line app/vmalert/web.qtpl:196
					qw422016.N().S(`
                                                    `)
//line app/vmalert/web.qtpl:197
				} else {
//line app/vmalert/web.qtpl:197
					qw422016.N().S(`
                                                        <b>record:</b> `)
//line app/vmalert/web.qtpl:198
					qw422016.E().S(r.Name)
//line app/vmalert/web.qtpl:198
					qw422016.N().S(`
                                                    `)
//line app/vmalert/web.qtpl:199
				}
//line app/vmalert/web.qtpl:199
				qw422016.N().S(`
                                                </div>
                                                <div class="col-12">
                                                    <code><pre>`)
//line app/vmalert/web.qtpl:202
				qw422016.E().S(r.Query)
//line app/vmalert/web.qtpl:202
				qw422016.N().S(`</pre></code>
                                                </div>
                                                <div class="col-12 mb-2">
                                                    `)
//line app/vmalert/web.qtpl:205
				if len(r.Labels) > 0 {
//line app/vmalert/web.qtpl:205
					qw422016.N().S(` <b>Labels:</b>`)
//line app/vmalert/web.qtpl:205
				}
//line app/vmalert/web.qtpl:205
				qw422016.N().S(`
                                                    `)
//line app/vmalert/web.qtpl:206
				for k, v := range r.Labels {
//line app/vmalert/web.qtpl:206
					qw422016.N().S(`
                                                        <span class="ms-1 badge bg-primary label">`)
//line app/vmalert/web.qtpl:207
					qw422016.E().S(k)
//line app/vmalert/web.qtpl:207
					qw422016.N().S(`=`)
//line app/vmalert/web.qtpl:207
					qw422016.E().S(v)
//line app/vmalert/web.qtpl:207
					qw422016.N().S(`</span>
                                                    `)
//line app/vmalert/web.qtpl:208
				}
//line app/vmalert/web.qtpl:208
				qw422016.N().S(`
                                                </div>
                                                `)
//line app/vmalert/web.qtpl:210
				if r.LastError != "" {
//line app/vmalert/web.qtpl:210
					qw422016.N().S(`
                                                    <div class="col-12">
                                                        <b>Error:</b>
                                                        <div class="error-cell">
                                                            `)
//line app/vmalert/web.qtpl:214
					qw422016.E().S(r.LastError)
//line app/vmalert/web.qtpl:214
					qw422016.N().S(`
                                                        </div>
                                                    </div>
                                                `)
//line app/vmalert/web.qtpl:217
				}
//line app/vmalert/web.qtpl:217
				qw422016.N().S(`
                                            </div>
                                        </td>
                                        <td class="text-center">`)
//line app/vmalert/web.qtpl:220
				qw422016.N().D(r.LastSamples)
//line app/vmalert/web.qtpl:220
				qw422016.N().S(`</td>
                                        <td class="text-center">`)
//line app/vmalert/web.qtpl:221
				if r.LastEvaluation.IsZero() {
//line app/vmalert/web.qtpl:221
					qw422016.N().S(`
                                             Never
                                         `)
//line app/vmalert/web.qtpl:223
				} else {
//line app/vmalert/web.qtpl:223
					qw422016.N().S(`
                                            `)
//line app/vmalert/web.qtpl:224
					qw422016.N().FPrec(time.Since(r.LastEvaluation).Seconds(), 3)
//line app/vmalert/web.qtpl:224
					qw422016.N().S(`s ago
                                         `)
//line app/vmalert/web.qtpl:225
				}
//line app/vmalert/web.qtpl:225
				qw422016.N().S(`
                                        </td>
                                        <td class="text-end align-middle">
                                            `)
//line app/vmalert/web.qtpl:228
				streamseriesFetchedWarn(qw422016, prefix, r)
//line app/vmalert/web.qtpl:228
				qw422016.N().S(`
                                            `)
//line app/vmalert/web.qtpl:229
				streamdetails(qw422016, prefix, r.WebLink())
//line app/vmalert/web.qtpl:229
				qw422016.N().S(`
                                        </td>
                                    </tr>
                                `)
//line app/vmalert/web.qtpl:232
			}
//line app/vmalert/web.qtpl:232
			qw422016.N().S(`
                            </tbody>
                        </table>
                    </div>
                </div>
            `)
//line app/vmalert/web.qtpl:237
		}
//line app/vmalert/web.qtpl:237
		qw422016.N().S(`
        `)
//line app/vmalert/web.qtpl:238
	} else {
//line app/vmalert/web.qtpl:238
		qw422016.N().S(`
            <div>
                <p>No groups...</p>
            </div>
        `)
//line app/vmalert/web.qtpl:242
	}
//line app/vmalert/web.qtpl:242
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:243
	tpl.StreamFooter(qw422016, r)
//line app/vmalert/web.qtpl:243
	qw422016.N().S(`
`)
//line app/vmalert/web.qtpl:244
}

//line app/vmalert/web.qtpl:244
func WriteListGroups(qq422016 qtio422016.Writer, r *http.Request, groups []*rule.ApiGroup, filter string) {
//line app/vmalert/web.qtpl:244
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vmalert/web.qtpl:244
	StreamListGroups(qw422016, r, groups, filter)
//line app/vmalert/web.qtpl:244
	qt422016.ReleaseWriter(qw422016)
//line app/vmalert/web.qtpl:244
}

//line app/vmalert/web.qtpl:244
func ListGroups(r *http.Request, groups []*rule.ApiGroup, filter string) string {
//line app/vmalert/web.qtpl:244
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vmalert/web.qtpl:244
	WriteListGroups(qb422016, r, groups, filter)
//line app/vmalert/web.qtpl:244
	qs422016 := string(qb422016.B)
//line app/vmalert/web.qtpl:244
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vmalert/web.qtpl:244
	return qs422016
//line app/vmalert/web.qtpl:244
}

//line app/vmalert/web.qtpl:247
func StreamListAlerts(qw422016 *qt422016.Writer, r *http.Request, groupAlerts []rule.GroupAlerts) {
//line app/vmalert/web.qtpl:247
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:248
	prefix := vmalertutil.Prefix(r.URL.Path)

//line app/vmalert/web.qtpl:248
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:249
	tpl.StreamHeader(qw422016, r, navItems, "Alerts", getLastConfigError())
//line app/vmalert/web.qtpl:249
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:250
	StreamControls(qw422016, prefix, "", "", nil, nil, true)
//line app/vmalert/web.qtpl:250
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:251
	if len(groupAlerts) > 0 {
//line app/vmalert/web.qtpl:251
		qw422016.N().S(`
         `)
//line app/vmalert/web.qtpl:252
		for _, ga := range groupAlerts {
//line app/vmalert/web.qtpl:252
			qw422016.N().S(`
             `)
//line app/vmalert/web.qtpl:254
			g := ga.Group
			var keys []string
			alertsByRule := make(map[string][]*rule.ApiAlert)
			for _, alert := range ga.Alerts {
				if len(alertsByRule[alert.RuleID]) < 1 {
					keys = append(keys, alert.RuleID)
				}
				alertsByRule[alert.RuleID] = append(alertsByRule[alert.RuleID], alert)
			}
			sort.Strings(keys)

//line app/vmalert/web.qtpl:264
			qw422016.N().S(`
             <div class="w-100 flex-column vm-group alert-danger">
                 <span id="group-`)
//line app/vmalert/web.qtpl:266
			qw422016.E().S(g.ID)
//line app/vmalert/web.qtpl:266
			qw422016.N().S(`" class="d-flex justify-content-between">
                     <a href="#group-`)
//line app/vmalert/web.qtpl:267
			qw422016.E().S(g.ID)
//line app/vmalert/web.qtpl:267
			qw422016.N().S(`">`)
//line app/vmalert/web.qtpl:267
			qw422016.E().S(g.Name)
//line app/vmalert/web.qtpl:267
			if g.Type != "prometheus" {
//line app/vmalert/web.qtpl:267
				qw422016.N().S(` (`)
//line app/vmalert/web.qtpl:267
				qw422016.E().S(g.Type)
//line app/vmalert/web.qtpl:267
				qw422016.N().S(`)`)
//line app/vmalert/web.qtpl:267
			}
//line app/vmalert/web.qtpl:267
			qw422016.N().S(`</a>
                     <span
                         class="flex-grow-1 d-flex justify-content-end"
                         role="button"
                         data-bs-toggle="collapse"
                         data-bs-target="#item-`)
//line app/vmalert/web.qtpl:272
			qw422016.E().S(g.ID)
//line app/vmalert/web.qtpl:272
			qw422016.N().S(`"
                     >
                         <span class="badge bg-danger" title="Number of active alerts">`)
//line app/vmalert/web.qtpl:274
			qw422016.N().D(len(ga.Alerts))
//line app/vmalert/web.qtpl:274
			qw422016.N().S(`</span>
                     </span>
                 </span>
                 <span>
                     <span
                         class="fs-6 text-start w-100 fw-lighter"
                         role="button" 
                         data-bs-toggle="collapse"
                         data-bs-target="#item-`)
//line app/vmalert/web.qtpl:282
			qw422016.E().S(g.ID)
//line app/vmalert/web.qtpl:282
			qw422016.N().S(`"
                     >`)
//line app/vmalert/web.qtpl:283
			qw422016.E().S(g.File)
//line app/vmalert/web.qtpl:283
			qw422016.N().S(`</span>
                 </span>
                 <div class="collapse" id="item-`)
//line app/vmalert/web.qtpl:285
			qw422016.E().S(g.ID)
//line app/vmalert/web.qtpl:285
			qw422016.N().S(`">
                     `)
//line app/vmalert/web.qtpl:286
			for _, ruleID := range keys {
//line app/vmalert/web.qtpl:286
				qw422016.N().S(`
                         `)
//line app/vmalert/web.qtpl:288
				defaultAR := alertsByRule[ruleID][0]
				var labelKeys []string
				for k := range defaultAR.Labels {
					labelKeys = append(labelKeys, k)
				}
				sort.Strings(labelKeys)

//line app/vmalert/web.qtpl:294
				qw422016.N().S(`
                         <br>
                         <div class="vm-item">
                             <b>alert:</b> `)
//line app/vmalert/web.qtpl:297
				qw422016.E().S(defaultAR.Name)
//line app/vmalert/web.qtpl:297
				qw422016.N().S(` (`)
//line app/vmalert/web.qtpl:297
				qw422016.N().D(len(alertsByRule[ruleID]))
//line app/vmalert/web.qtpl:297
				qw422016.N().S(`)
                             | <span><a target="_blank" href="`)
//line app/vmalert/web.qtpl:298
				qw422016.E().S(defaultAR.SourceLink)
//line app/vmalert/web.qtpl:298
				qw422016.N().S(`">Source</a></span>
                             <br>
                             <b>expr:</b><code><pre>`)
//line app/vmalert/web.qtpl:300
				qw422016.E().S(defaultAR.Expression)
//line app/vmalert/web.qtpl:300
				qw422016.N().S(`</pre></code>
                             <table class="table table-striped table-hover table-sm">
                                 <thead>
                                     <tr>
                                         <th class="w-50" scope="col">Labels</th>
                                         <th scope="col">State</th>
                                         <th scope="col">Active at</th>
                                         <th scope="col">Value</th>
                                         <th class="w-10" scope="col">Link</th>
                                     </tr>
                                 </thead>
                                 <tbody>
                                     `)
//line app/vmalert/web.qtpl:312
				for _, ar := range alertsByRule[ruleID] {
//line app/vmalert/web.qtpl:312
					qw422016.N().S(`
                                         <tr>
                                             <td>
                                                 `)
//line app/vmalert/web.qtpl:315
					for _, k := range labelKeys {
//line app/vmalert/web.qtpl:315
						qw422016.N().S(`
                                                     <span class="ms-1 badge bg-primary label">`)
//line app/vmalert/web.qtpl:316
						qw422016.E().S(k)
//line app/vmalert/web.qtpl:316
						qw422016.N().S(`=`)
//line app/vmalert/web.qtpl:316
						qw422016.E().S(ar.Labels[k])
//line app/vmalert/web.qtpl:316
						qw422016.N().S(`</span>
                                                 `)
//line app/vmalert/web.qtpl:317
					}
//line app/vmalert/web.qtpl:317
					qw422016.N().S(`
                                             </td>
                                             <td>`)
//line app/vmalert/web.qtpl:319
					streambadgeState(qw422016, ar.State)
//line app/vmalert/web.qtpl:319
					qw422016.N().S(`</td>
                                             <td>
                                                 `)
//line app/vmalert/web.qtpl:321
					qw422016.E().S(ar.ActiveAt.Format("2006-01-02T15:04:05Z07:00"))
//line app/vmalert/web.qtpl:321
					qw422016.N().S(`
                                                 `)
//line app/vmalert/web.qtpl:322
					if ar.Restored {
//line app/vmalert/web.qtpl:322
						streambadgeRestored(qw422016)
//line app/vmalert/web.qtpl:322
					}
//line app/vmalert/web.qtpl:322
					qw422016.N().S(`
                                                 `)
//line app/vmalert/web.qtpl:323
					if ar.Stabilizing {
//line app/vmalert/web.qtpl:323
						streambadgeStabilizing(qw422016)
//line app/vmalert/web.qtpl:323
					}
//line app/vmalert/web.qtpl:323
					qw422016.N().S(`
                                             </td>
                                             <td>`)
//line app/vmalert/web.qtpl:325
					qw422016.E().S(ar.Value)
//line app/vmalert/web.qtpl:325
					qw422016.N().S(`</td>
                                             <td>`)
//line app/vmalert/web.qtpl:326
					streamdetails(qw422016, prefix, ar.WebLink())
//line app/vmalert/web.qtpl:326
					qw422016.N().S(`</td>
                                         </tr>
                                     `)
//line app/vmalert/web.qtpl:328
				}
//line app/vmalert/web.qtpl:328
				qw422016.N().S(`
                                 </tbody>
                             </table>
                         </div>
                     `)
//line app/vmalert/web.qtpl:332
			}
//line app/vmalert/web.qtpl:332
			qw422016.N().S(`
                 </div>
             </div>
         `)
//line app/vmalert/web.qtpl:335
		}
//line app/vmalert/web.qtpl:335
		qw422016.N().S(`
     `)
//line app/vmalert/web.qtpl:336
	} else {
//line app/vmalert/web.qtpl:336
		qw422016.N().S(`
         <div>
             <p>No active alerts...</p>
         </div>
     `)
//line app/vmalert/web.qtpl:340
	}
//line app/vmalert/web.qtpl:340
	qw422016.N().S(`
     `)
//line app/vmalert/web.qtpl:341
	tpl.StreamFooter(qw422016, r)
//line app/vmalert/web.qtpl:341
	qw422016.N().S(`
`)
//line app/vmalert/web.qtpl:342
}

//line app/vmalert/web.qtpl:342
func WriteListAlerts(qq422016 qtio422016.Writer, r *http.Request, groupAlerts []rule.GroupAlerts) {
//line app/vmalert/web.qtpl:342
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vmalert/web.qtpl:342
	StreamListAlerts(qw422016, r, groupAlerts)
//line app/vmalert/web.qtpl:342
	qt422016.ReleaseWriter(qw422016)
//line app/vmalert/web.qtpl:342
}

//line app/vmalert/web.qtpl:342
func ListAlerts(r *http.Request, groupAlerts []rule.GroupAlerts) string {
//line app/vmalert/web.qtpl:342
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vmalert/web.qtpl:342
	WriteListAlerts(qb422016, r, groupAlerts)
//line app/vmalert/web.qtpl:342
	qs422016 := string(qb422016.B)
//line app/vmalert/web.qtpl:342
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vmalert/web.qtpl:342
	return qs422016
//line app/vmalert/web.qtpl:342
}

//line app/vmalert/web.qtpl:344
func StreamListTargets(qw422016 *qt422016.Writer, r *http.Request, targets map[notifier.TargetType][]notifier.Target) {
//line app/vmalert/web.qtpl:344
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:345
	prefix := vmalertutil.Prefix(r.URL.Path)

//line app/vmalert/web.qtpl:345
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:346
	tpl.StreamHeader(qw422016, r, navItems, "Notifiers", getLastConfigError())
//line app/vmalert/web.qtpl:346
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:347
	StreamControls(qw422016, prefix, "", "", nil, nil, false)
//line app/vmalert/web.qtpl:347
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:348
	if len(targets) > 0 {
//line app/vmalert/web.qtpl:348
		qw422016.N().S(`
        `)
//line app/vmalert/web.qtpl:350
		var keys []string
		for key := range targets {
			keys = append(keys, string(key))
		}
		sort.Strings(keys)

//line app/vmalert/web.qtpl:355
		qw422016.N().S(`
        `)
//line app/vmalert/web.qtpl:356
		for i := range keys {
//line app/vmalert/web.qtpl:356
			qw422016.N().S(`
            `)
//line app/vmalert/web.qtpl:358
			typeK, ns := keys[i], targets[notifier.TargetType(keys[i])]
			count := len(ns)

//line app/vmalert/web.qtpl:360
			qw422016.N().S(`
            <div class="w-100 flex-column vm-group">
                <span class="d-flex justify-content-between" id="group-`)
//line app/vmalert/web.qtpl:362
			qw422016.E().S(typeK)
//line app/vmalert/web.qtpl:362
			qw422016.N().S(`">
                    <a href="#group-`)
//line app/vmalert/web.qtpl:363
			qw422016.E().S(typeK)
//line app/vmalert/web.qtpl:363
			qw422016.N().S(`">`)
//line app/vmalert/web.qtpl:363
			qw422016.E().S(typeK)
//line app/vmalert/web.qtpl:363
			qw422016.N().S(` (`)
//line app/vmalert/web.qtpl:363
			qw422016.N().D(count)
//line app/vmalert/web.qtpl:363
			qw422016.N().S(`)</a>
                    <span
                        class="flex-grow-1"
                        role="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#item-`)
//line app/vmalert/web.qtpl:368
			qw422016.E().S(typeK)
//line app/vmalert/web.qtpl:368
			qw422016.N().S(`"
                    ></span>
                </span>
                <div id="item-`)
//line app/vmalert/web.qtpl:371
			qw422016.E().S(typeK)
//line app/vmalert/web.qtpl:371
			qw422016.N().S(`" class="collapse show">
                    <table class="table table-striped table-hover table-sm">
                        <thead>
                            <tr class="vm-item">
                                <th scope="col">Labels</th>
                                <th scope="col">Address</th>
                            </tr>
                        </thead>
                        <tbody>
                            `)
//line app/vmalert/web.qtpl:380
			for _, n := range ns {
//line app/vmalert/web.qtpl:380
				qw422016.N().S(`
                                <tr>
                                    <td>
                                        `)
//line app/vmalert/web.qtpl:383
				for _, l := range n.Labels.GetLabels() {
//line app/vmalert/web.qtpl:383
					qw422016.N().S(`
                                            <span class="ms-1 badge bg-primary">`)
//line app/vmalert/web.qtpl:384
					qw422016.E().S(l.Name)
//line app/vmalert/web.qtpl:384
					qw422016.N().S(`=`)
//line app/vmalert/web.qtpl:384
					qw422016.E().S(l.Value)
//line app/vmalert/web.qtpl:384
					qw422016.N().S(`</span>
                                        `)
//line app/vmalert/web.qtpl:385
				}
//line app/vmalert/web.qtpl:385
				qw422016.N().S(`
                                    </td>
                                    <td>`)
//line app/vmalert/web.qtpl:387
				qw422016.E().S(n.Notifier.Addr())
//line app/vmalert/web.qtpl:387
				qw422016.N().S(`</td>
                                </tr>
                            `)
//line app/vmalert/web.qtpl:389
			}
//line app/vmalert/web.qtpl:389
			qw422016.N().S(`
                        </tbody>
                    </table>
                </div>
            </div>
        `)
//line app/vmalert/web.qtpl:394
		}
//line app/vmalert/web.qtpl:394
		qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:395
	} else {
//line app/vmalert/web.qtpl:395
		qw422016.N().S(`
        <div>
            <p>No targets...</p>
        </div>
    `)
//line app/vmalert/web.qtpl:399
	}
//line app/vmalert/web.qtpl:399
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:400
	tpl.StreamFooter(qw422016, r)
//line app/vmalert/web.qtpl:400
	qw422016.N().S(`
`)
//line app/vmalert/web.qtpl:401
}

//line app/vmalert/web.qtpl:401
func WriteListTargets(qq422016 qtio422016.Writer, r *http.Request, targets map[notifier.TargetType][]notifier.Target) {
//line app/vmalert/web.qtpl:401
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vmalert/web.qtpl:401
	StreamListTargets(qw422016, r, targets)
//line app/vmalert/web.qtpl:401
	qt422016.ReleaseWriter(qw422016)
//line app/vmalert/web.qtpl:401
}

//line app/vmalert/web.qtpl:401
func ListTargets(r *http.Request, targets map[notifier.TargetType][]notifier.Target) string {
//line app/vmalert/web.qtpl:401
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vmalert/web.qtpl:401
	WriteListTargets(qb422016, r, targets)
//line app/vmalert/web.qtpl:401
	qs422016 := string(qb422016.B)
//line app/vmalert/web.qtpl:401
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vmalert/web.qtpl:401
	return qs422016
//line app/vmalert/web.qtpl:401
}

//line app/vmalert/web.qtpl:403
func StreamAlert(qw422016 *qt422016.Writer, r *http.Request, alert *rule.ApiAlert) {
//line app/vmalert/web.qtpl:403
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:404
	prefix := vmalertutil.Prefix(r.URL.Path)

//line app/vmalert/web.qtpl:404
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:405
	tpl.StreamHeader(qw422016, r, navItems, "", getLastConfigError())
//line app/vmalert/web.qtpl:405
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:407
	var labelKeys []string
	for k := range alert.Labels {
		labelKeys = append(labelKeys, k)
	}
	sort.Strings(labelKeys)
	var annotationKeys []string
	for k := range alert.Annotations {
		annotationKeys = append(annotationKeys, k)
	}
	sort.Strings(annotationKeys)

//line app/vmalert/web.qtpl:417
	qw422016.N().S(`
    <div class="display-6 pb-3 mb-3">Alert: `)
//line app/vmalert/web.qtpl:418
	qw422016.E().S(alert.Name)
//line app/vmalert/web.qtpl:418
	qw422016.N().S(`<span class="ms-2 badge `)
//line app/vmalert/web.qtpl:418
	if alert.State == "firing" {
//line app/vmalert/web.qtpl:418
		qw422016.N().S(`bg-danger`)
//line app/vmalert/web.qtpl:418
	} else {
//line app/vmalert/web.qtpl:418
		qw422016.N().S(` bg-warning text-dark`)
//line app/vmalert/web.qtpl:418
	}
//line app/vmalert/web.qtpl:418
	qw422016.N().S(`">`)
//line app/vmalert/web.qtpl:418
	qw422016.E().S(alert.State)
//line app/vmalert/web.qtpl:418
	qw422016.N().S(`</span></div>
    <div class="container border-bottom p-2">
      <div class="row">
        <div class="col-2">
          Active at
        </div>
        <div class="col">
          `)
//line app/vmalert/web.qtpl:425
	qw422016.E().S(alert.ActiveAt.Format("2006-01-02T15:04:05Z07:00"))
//line app/vmalert/web.qtpl:425
	qw422016.N().S(`
        </div>
      </div>
      </div>
    <div class="container border-bottom p-2">
      <div class="row">
        <div class="col-2">
          Expr
        </div>
        <div class="col">
          <code><pre>`)
//line app/vmalert/web.qtpl:435
	qw422016.E().S(alert.Expression)
//line app/vmalert/web.qtpl:435
	qw422016.N().S(`</pre></code>
        </div>
      </div>
    </div>
    <div class="container border-bottom p-2">
      <div class="row">
        <div class="col-2">
          Labels
        </div>
        <div class="col">
           `)
//line app/vmalert/web.qtpl:445
	for _, k := range labelKeys {
//line app/vmalert/web.qtpl:445
		qw422016.N().S(`
                <span class="m-1 badge bg-primary">`)
//line app/vmalert/web.qtpl:446
		qw422016.E().S(k)
//line app/vmalert/web.qtpl:446
		qw422016.N().S(`=`)
//line app/vmalert/web.qtpl:446
		qw422016.E().S(alert.Labels[k])
//line app/vmalert/web.qtpl:446
		qw422016.N().S(`</span>
          `)
//line app/vmalert/web.qtpl:447
	}
//line app/vmalert/web.qtpl:447
	qw422016.N().S(`
        </div>
      </div>
    </div>
    <div class="container border-bottom p-2">
      <div class="row">
        <div class="col-2">
          Annotations
        </div>
        <div class="col">
           `)
//line app/vmalert/web.qtpl:457
	for _, k := range annotationKeys {
//line app/vmalert/web.qtpl:457
		qw422016.N().S(`
                <b>`)
//line app/vmalert/web.qtpl:458
		qw422016.E().S(k)
//line app/vmalert/web.qtpl:458
		qw422016.N().S(`:</b><br>
                <p class="annotations">`)
//line app/vmalert/web.qtpl:459
		qw422016.E().S(alert.Annotations[k])
//line app/vmalert/web.qtpl:459
		qw422016.N().S(`</p>
          `)
//line app/vmalert/web.qtpl:460
	}
//line app/vmalert/web.qtpl:460
	qw422016.N().S(`
        </div>
      </div>
    </div>
    <div class="container border-bottom p-2">
      <div class="row">
        <div class="col-2">
          Group
        </div>
        <div class="col">
           <a target="_blank" href="`)
//line app/vmalert/web.qtpl:470
	qw422016.E().S(prefix)
//line app/vmalert/web.qtpl:470
	qw422016.N().S(`groups#group-`)
//line app/vmalert/web.qtpl:470
	qw422016.E().S(alert.GroupID)
//line app/vmalert/web.qtpl:470
	qw422016.N().S(`">`)
//line app/vmalert/web.qtpl:470
	qw422016.E().S(alert.GroupID)
//line app/vmalert/web.qtpl:470
	qw422016.N().S(`</a>
        </div>
      </div>
    </div>
     <div class="container border-bottom p-2">
      <div class="row">
        <div class="col-2">
          Source link
        </div>
        <div class="col">
           <a target="_blank" href="`)
//line app/vmalert/web.qtpl:480
	qw422016.E().S(alert.SourceLink)
//line app/vmalert/web.qtpl:480
	qw422016.N().S(`">Link</a>
        </div>
      </div>
    </div>
    `)
//line app/vmalert/web.qtpl:484
	tpl.StreamFooter(qw422016, r)
//line app/vmalert/web.qtpl:484
	qw422016.N().S(`

`)
//line app/vmalert/web.qtpl:486
}

//line app/vmalert/web.qtpl:486
func WriteAlert(qq422016 qtio422016.Writer, r *http.Request, alert *rule.ApiAlert) {
//line app/vmalert/web.qtpl:486
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vmalert/web.qtpl:486
	StreamAlert(qw422016, r, alert)
//line app/vmalert/web.qtpl:486
	qt422016.ReleaseWriter(qw422016)
//line app/vmalert/web.qtpl:486
}

//line app/vmalert/web.qtpl:486
func Alert(r *http.Request, alert *rule.ApiAlert) string {
//line app/vmalert/web.qtpl:486
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vmalert/web.qtpl:486
	WriteAlert(qb422016, r, alert)
//line app/vmalert/web.qtpl:486
	qs422016 := string(qb422016.B)
//line app/vmalert/web.qtpl:486
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vmalert/web.qtpl:486
	return qs422016
//line app/vmalert/web.qtpl:486
}

//line app/vmalert/web.qtpl:489
func StreamRuleDetails(qw422016 *qt422016.Writer, r *http.Request, rule rule.ApiRule) {
//line app/vmalert/web.qtpl:489
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:490
	prefix := vmalertutil.Prefix(r.URL.Path)

//line app/vmalert/web.qtpl:490
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:491
	tpl.StreamHeader(qw422016, r, navItems, "", getLastConfigError())
//line app/vmalert/web.qtpl:491
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:493
	var labelKeys []string
	for k := range rule.Labels {
		labelKeys = append(labelKeys, k)
	}
	sort.Strings(labelKeys)

	var annotationKeys []string
	for k := range rule.Annotations {
		annotationKeys = append(annotationKeys, k)
	}
	sort.Strings(annotationKeys)

	var seriesFetchedEnabled bool
	var seriesFetchedWarning bool
	for _, u := range rule.Updates {
		if u.SeriesFetched != nil {
			seriesFetchedEnabled = true
			if *u.SeriesFetched == 0 && u.Samples == 0 {
				seriesFetchedWarning = true
			}
		}
	}

//line app/vmalert/web.qtpl:516
	qw422016.N().S(`
    <div class="display-6 pb-3 mb-3">Rule: `)
//line app/vmalert/web.qtpl:517
	qw422016.E().S(rule.Name)
//line app/vmalert/web.qtpl:517
	qw422016.N().S(`<span class="ms-2 badge `)
//line app/vmalert/web.qtpl:517
	if rule.Health != "ok" {
//line app/vmalert/web.qtpl:517
		qw422016.N().S(`bg-danger`)
//line app/vmalert/web.qtpl:517
	} else {
//line app/vmalert/web.qtpl:517
		qw422016.N().S(` bg-success text-dark`)
//line app/vmalert/web.qtpl:517
	}
//line app/vmalert/web.qtpl:517
	qw422016.N().S(`">`)
//line app/vmalert/web.qtpl:517
	qw422016.E().S(rule.Health)
//line app/vmalert/web.qtpl:517
	qw422016.N().S(`</span></div>
    <div class="container border-bottom p-2">
      <div class="row">
        <div class="col-2">
          Expr
        </div>
        <div class="col">
          <code><pre>`)
//line app/vmalert/web.qtpl:524
	qw422016.E().S(rule.Query)
//line app/vmalert/web.qtpl:524
	qw422016.N().S(`</pre></code>
        </div>
      </div>
    </div>
    `)
//line app/vmalert/web.qtpl:528
	if rule.Type == "alerting" {
//line app/vmalert/web.qtpl:528
		qw422016.N().S(`
    <div class="container border-bottom p-2">
      <div class="row">
        <div class="col-2">
          For
        </div>
        <div class="col">
         `)
//line app/vmalert/web.qtpl:535
		qw422016.E().V(rule.Duration)
//line app/vmalert/web.qtpl:535
		qw422016.N().S(` seconds
        </div>
      </div>
    </div>
    `)
//line app/vmalert/web.qtpl:539
		if rule.KeepFiringFor > 0 {
//line app/vmalert/web.qtpl:539
			qw422016.N().S(`
    <div class="container border-bottom p-2">
      <div class="row">
        <div class="col-2">
          Keep firing for
        </div>
        <div class="col">
         `)
//line app/vmalert/web.qtpl:546
			qw422016.E().V(rule.KeepFiringFor)
//line app/vmalert/web.qtpl:546
			qw422016.N().S(` seconds
        </div>
      </div>
    </div>
    `)
//line app/vmalert/web.qtpl:550
		}
//line app/vmalert/web.qtpl:550
		qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:551
	}
//line app/vmalert/web.qtpl:551
	qw422016.N().S(`
    <div class="container border-bottom p-2">
      <div class="row">
        <div class="col-2">
          Labels
        </div>
        <div class="col">
          `)
//line app/vmalert/web.qtpl:558
	for _, k := range labelKeys {
//line app/vmalert/web.qtpl:558
		qw422016.N().S(`
                <span class="m-1 badge bg-primary">`)
//line app/vmalert/web.qtpl:559
		qw422016.E().S(k)
//line app/vmalert/web.qtpl:559
		qw422016.N().S(`=`)
//line app/vmalert/web.qtpl:559
		qw422016.E().S(rule.Labels[k])
//line app/vmalert/web.qtpl:559
		qw422016.N().S(`</span>
          `)
//line app/vmalert/web.qtpl:560
	}
//line app/vmalert/web.qtpl:560
	qw422016.N().S(`
        </div>
      </div>
    </div>
    `)
//line app/vmalert/web.qtpl:564
	if rule.Type == "alerting" {
//line app/vmalert/web.qtpl:564
		qw422016.N().S(`
    <div class="container border-bottom p-2">
      <div class="row">
        <div class="col-2">
          Annotations
        </div>
        <div class="col">
          `)
//line app/vmalert/web.qtpl:571
		for _, k := range annotationKeys {
//line app/vmalert/web.qtpl:571
			qw422016.N().S(`
                <b>`)
//line app/vmalert/web.qtpl:572
			qw422016.E().S(k)
//line app/vmalert/web.qtpl:572
			qw422016.N().S(`:</b><br>
                <p class="annotations">`)
//line app/vmalert/web.qtpl:573
			qw422016.E().S(rule.Annotations[k])
//line app/vmalert/web.qtpl:573
			qw422016.N().S(`</p>
          `)
//line app/vmalert/web.qtpl:574
		}
//line app/vmalert/web.qtpl:574
		qw422016.N().S(`
        </div>
      </div>
    </div>
    <div class="container border-bottom p-2">
      <div class="row">
        <div class="col-2">
          Debug
        </div>
        <div class="col">
           `)
//line app/vmalert/web.qtpl:584
		qw422016.E().V(rule.Debug)
//line app/vmalert/web.qtpl:584
		qw422016.N().S(`
        </div>
      </div>
    </div>
    `)
//line app/vmalert/web.qtpl:588
	}
//line app/vmalert/web.qtpl:588
	qw422016.N().S(`
    <div class="container border-bottom p-2">
      <div class="row">
        <div class="col-2">
          Group
        </div>
        <div class="col">
           <a target="_blank" href="`)
//line app/vmalert/web.qtpl:595
	qw422016.E().S(prefix)
//line app/vmalert/web.qtpl:595
	qw422016.N().S(`groups#group-`)
//line app/vmalert/web.qtpl:595
	qw422016.E().S(rule.GroupID)
//line app/vmalert/web.qtpl:595
	qw422016.N().S(`">`)
//line app/vmalert/web.qtpl:595
	qw422016.E().S(rule.GroupID)
//line app/vmalert/web.qtpl:595
	qw422016.N().S(`</a>
        </div>
      </div>
    </div>

    <br>
    `)
//line app/vmalert/web.qtpl:601
	if seriesFetchedWarning {
//line app/vmalert/web.qtpl:601
		qw422016.N().S(`
    <div class="alert alert-warning" role="alert">
       <strong>Warning:</strong> some of updates have "Series fetched" equal to 0.<br>
       It might be that either this data is missing in the datasource or there is a typo in rule's expression.
       For example, <strong>foo{label="bar"} > 0</strong> could never trigger because <strong>foo{label="bar"}</strong>
       metric doesn't exist.
       <br>
       Rule's expressions without time series selector, like <strong>expr: 42</strong> or <strong>expr: time()</strong>
       aren't fetching time series from datasource, so they could have "Series fetched" equal to 0 and this won't be a problem.
       <br>
       See more details about this detection <a target="_blank" href="https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4039">here</a>.
    </div>
    `)
//line app/vmalert/web.qtpl:613
	}
//line app/vmalert/web.qtpl:613
	qw422016.N().S(`
    <div class="display-6 pb-3">Last `)
//line app/vmalert/web.qtpl:614
	qw422016.N().D(len(rule.Updates))
//line app/vmalert/web.qtpl:614
	qw422016.N().S(`/`)
//line app/vmalert/web.qtpl:614
	qw422016.N().D(rule.MaxUpdates)
//line app/vmalert/web.qtpl:614
	qw422016.N().S(` updates</span>:</div>
        <table class="table table-striped table-hover table-sm">
            <thead>
                <tr>
                    <th scope="col" title="The time when the rule was executed">Updated at</th>
                    <th scope="col" class="w-10 text-center" title="How many series expression returns. Each series will represent an alert.">Series returned</th>
                    `)
//line app/vmalert/web.qtpl:620
	if seriesFetchedEnabled {
//line app/vmalert/web.qtpl:620
		qw422016.N().S(`<th scope="col" class="w-10 text-center" title="How many series were scanned by datasource during the evaluation">Series fetched</th>`)
//line app/vmalert/web.qtpl:620
	}
//line app/vmalert/web.qtpl:620
	qw422016.N().S(`
                    <th scope="col" class="w-10 text-center" title="How many seconds request took">Duration</th>
                    <th scope="col" class="text-center" title="The time used in execution query request">Execution timestamp</th>
                    <th scope="col" class="text-center" title="cURL command with request example">cURL</th>
                </tr>
            </thead>
            <tbody>

     `)
//line app/vmalert/web.qtpl:628
	for _, u := range rule.Updates {
//line app/vmalert/web.qtpl:628
		qw422016.N().S(`
             <tr`)
//line app/vmalert/web.qtpl:629
		if u.Err != nil {
//line app/vmalert/web.qtpl:629
			qw422016.N().S(` class="alert-danger"`)
//line app/vmalert/web.qtpl:629
		}
//line app/vmalert/web.qtpl:629
		qw422016.N().S(`>
                 <td>
                    <span class="badge bg-primary rounded-pill me-3" title="Updated at">`)
//line app/vmalert/web.qtpl:631
		qw422016.E().S(u.Time.Format(time.RFC3339))
//line app/vmalert/web.qtpl:631
		qw422016.N().S(`</span>
                 </td>
                 <td class="text-center">`)
//line app/vmalert/web.qtpl:633
		qw422016.N().D(u.Samples)
//line app/vmalert/web.qtpl:633
		qw422016.N().S(`</td>
                 `)
//line app/vmalert/web.qtpl:634
		if seriesFetchedEnabled {
//line app/vmalert/web.qtpl:634
			qw422016.N().S(`<td class="text-center">`)
//line app/vmalert/web.qtpl:634
			if u.SeriesFetched != nil {
//line app/vmalert/web.qtpl:634
				qw422016.N().D(*u.SeriesFetched)
//line app/vmalert/web.qtpl:634
			}
//line app/vmalert/web.qtpl:634
			qw422016.N().S(`</td>`)
//line app/vmalert/web.qtpl:634
		}
//line app/vmalert/web.qtpl:634
		qw422016.N().S(`
                 <td class="text-center">`)
//line app/vmalert/web.qtpl:635
		qw422016.N().FPrec(u.Duration.Seconds(), 3)
//line app/vmalert/web.qtpl:635
		qw422016.N().S(`s</td>
                 <td class="text-center">`)
//line app/vmalert/web.qtpl:636
		qw422016.E().S(u.At.Format(time.RFC3339))
//line app/vmalert/web.qtpl:636
		qw422016.N().S(`</td>
                 <td>
                    <textarea class="curl-area" rows="1" onclick="this.focus();this.select()">`)
//line app/vmalert/web.qtpl:638
		qw422016.E().S(u.Curl)
//line app/vmalert/web.qtpl:638
		qw422016.N().S(`</textarea>
                </td>
             </tr>
          </li>
          `)
//line app/vmalert/web.qtpl:642
		if u.Err != nil {
//line app/vmalert/web.qtpl:642
			qw422016.N().S(`
             <tr`)
//line app/vmalert/web.qtpl:643
			if u.Err != nil {
//line app/vmalert/web.qtpl:643
				qw422016.N().S(` class="alert-danger"`)
//line app/vmalert/web.qtpl:643
			}
//line app/vmalert/web.qtpl:643
			qw422016.N().S(`>
               <td colspan="`)
//line app/vmalert/web.qtpl:644
			if seriesFetchedEnabled {
//line app/vmalert/web.qtpl:644
				qw422016.N().S(`6`)
//line app/vmalert/web.qtpl:644
			} else {
//line app/vmalert/web.qtpl:644
				qw422016.N().S(`5`)
//line app/vmalert/web.qtpl:644
			}
//line app/vmalert/web.qtpl:644
			qw422016.N().S(`">
                   <span class="alert-danger">`)
//line app/vmalert/web.qtpl:645
			qw422016.E().V(u.Err)
//line app/vmalert/web.qtpl:645
			qw422016.N().S(`</span>
               </td>
             </tr>
          `)
//line app/vmalert/web.qtpl:648
		}
//line app/vmalert/web.qtpl:648
		qw422016.N().S(`
     `)
//line app/vmalert/web.qtpl:649
	}
//line app/vmalert/web.qtpl:649
	qw422016.N().S(`

    `)
//line app/vmalert/web.qtpl:651
	tpl.StreamFooter(qw422016, r)
//line app/vmalert/web.qtpl:651
	qw422016.N().S(`
`)
//line app/vmalert/web.qtpl:652
}

//line app/vmalert/web.qtpl:652
func WriteRuleDetails(qq422016 qtio422016.Writer, r *http.Request, rule rule.ApiRule) {
//line app/vmalert/web.qtpl:652
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vmalert/web.qtpl:652
	StreamRuleDetails(qw422016, r, rule)
//line app/vmalert/web.qtpl:652
	qt422016.ReleaseWriter(qw422016)
//line app/vmalert/web.qtpl:652
}

//line app/vmalert/web.qtpl:652
func RuleDetails(r *http.Request, rule rule.ApiRule) string {
//line app/vmalert/web.qtpl:652
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vmalert/web.qtpl:652
	WriteRuleDetails(qb422016, r, rule)
//line app/vmalert/web.qtpl:652
	qs422016 := string(qb422016.B)
//line app/vmalert/web.qtpl:652
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vmalert/web.qtpl:652
	return qs422016
//line app/vmalert/web.qtpl:652
}

//line app/vmalert/web.qtpl:656
func streambadgeState(qw422016 *qt422016.Writer, state string) {
//line app/vmalert/web.qtpl:656
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:658
	badgeClass := "bg-warning text-dark"
	if state == "firing" {
		badgeClass = "bg-danger"
	}

//line app/vmalert/web.qtpl:662
	qw422016.N().S(`
    <span class="badge `)
//line app/vmalert/web.qtpl:663
	qw422016.E().S(badgeClass)
//line app/vmalert/web.qtpl:663
	qw422016.N().S(`">`)
//line app/vmalert/web.qtpl:663
	qw422016.E().S(state)
//line app/vmalert/web.qtpl:663
	qw422016.N().S(`</span>
`)
//line app/vmalert/web.qtpl:664
}

//line app/vmalert/web.qtpl:664
func writebadgeState(qq422016 qtio422016.Writer, state string) {
//line app/vmalert/web.qtpl:664
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vmalert/web.qtpl:664
	streambadgeState(qw422016, state)
//line app/vmalert/web.qtpl:664
	qt422016.ReleaseWriter(qw422016)
//line app/vmalert/web.qtpl:664
}

//line app/vmalert/web.qtpl:664
func badgeState(state string) string {
//line app/vmalert/web.qtpl:664
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vmalert/web.qtpl:664
	writebadgeState(qb422016, state)
//line app/vmalert/web.qtpl:664
	qs422016 := string(qb422016.B)
//line app/vmalert/web.qtpl:664
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vmalert/web.qtpl:664
	return qs422016
//line app/vmalert/web.qtpl:664
}

//line app/vmalert/web.qtpl:666
func streambadgeRestored(qw422016 *qt422016.Writer) {
//line app/vmalert/web.qtpl:666
	qw422016.N().S(`
    <span class="badge bg-warning text-dark" title="Alert state was restored after the service restart from remote storage">restored</span>
`)
//line app/vmalert/web.qtpl:668
}

//line app/vmalert/web.qtpl:668
func writebadgeRestored(qq422016 qtio422016.Writer) {
//line app/vmalert/web.qtpl:668
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vmalert/web.qtpl:668
	streambadgeRestored(qw422016)
//line app/vmalert/web.qtpl:668
	qt422016.ReleaseWriter(qw422016)
//line app/vmalert/web.qtpl:668
}

//line app/vmalert/web.qtpl:668
func badgeRestored() string {
//line app/vmalert/web.qtpl:668
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vmalert/web.qtpl:668
	writebadgeRestored(qb422016)
//line app/vmalert/web.qtpl:668
	qs422016 := string(qb422016.B)
//line app/vmalert/web.qtpl:668
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vmalert/web.qtpl:668
	return qs422016
//line app/vmalert/web.qtpl:668
}

//line app/vmalert/web.qtpl:670
func streambadgeStabilizing(qw422016 *qt422016.Writer) {
//line app/vmalert/web.qtpl:670
	qw422016.N().S(`
    <span class="badge bg-warning text-dark" title="This firing state is kept because of `)
//line app/vmalert/web.qtpl:670
	qw422016.N().S("`")
//line app/vmalert/web.qtpl:670
	qw422016.N().S(`keep_firing_for`)
//line app/vmalert/web.qtpl:670
	qw422016.N().S("`")
//line app/vmalert/web.qtpl:670
	qw422016.N().S(`">stabilizing</span>
`)
//line app/vmalert/web.qtpl:672
}

//line app/vmalert/web.qtpl:672
func writebadgeStabilizing(qq422016 qtio422016.Writer) {
//line app/vmalert/web.qtpl:672
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vmalert/web.qtpl:672
	streambadgeStabilizing(qw422016)
//line app/vmalert/web.qtpl:672
	qt422016.ReleaseWriter(qw422016)
//line app/vmalert/web.qtpl:672
}

//line app/vmalert/web.qtpl:672
func badgeStabilizing() string {
//line app/vmalert/web.qtpl:672
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vmalert/web.qtpl:672
	writebadgeStabilizing(qb422016)
//line app/vmalert/web.qtpl:672
	qs422016 := string(qb422016.B)
//line app/vmalert/web.qtpl:672
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vmalert/web.qtpl:672
	return qs422016
//line app/vmalert/web.qtpl:672
}

//line app/vmalert/web.qtpl:674
func streamseriesFetchedWarn(qw422016 *qt422016.Writer, prefix string, r rule.ApiRule) {
//line app/vmalert/web.qtpl:674
	qw422016.N().S(`
    `)
//line app/vmalert/web.qtpl:675
	if isNoMatch(r) {
//line app/vmalert/web.qtpl:675
		qw422016.N().S(`
        <span class="no-match" title="This rule's last evaluation hasn't selected any time series from the datasource.
It might be that either this data is missing in the datasource or there is a typo in rule's expression.
See more in Details.">No match</span>
    `)
//line app/vmalert/web.qtpl:679
	}
//line app/vmalert/web.qtpl:679
	qw422016.N().S(`
`)
//line app/vmalert/web.qtpl:680
}

//line app/vmalert/web.qtpl:680
func writeseriesFetchedWarn(qq422016 qtio422016.Writer, prefix string, r rule.ApiRule) {
//line app/vmalert/web.qtpl:680
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vmalert/web.qtpl:680
	streamseriesFetchedWarn(qw422016, prefix, r)
//line app/vmalert/web.qtpl:680
	qt422016.ReleaseWriter(qw422016)
//line app/vmalert/web.qtpl:680
}

//line app/vmalert/web.qtpl:680
func seriesFetchedWarn(prefix string, r rule.ApiRule) string {
//line app/vmalert/web.qtpl:680
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vmalert/web.qtpl:680
	writeseriesFetchedWarn(qb422016, prefix, r)
//line app/vmalert/web.qtpl:680
	qs422016 := string(qb422016.B)
//line app/vmalert/web.qtpl:680
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vmalert/web.qtpl:680
	return qs422016
//line app/vmalert/web.qtpl:680
}

//line app/vmalert/web.qtpl:683
func isNoMatch(r rule.ApiRule) bool {
	return r.LastSamples == 0 && r.LastSeriesFetched != nil && *r.LastSeriesFetched == 0
}

//line app/vmalert/web.qtpl:688
func streamdetails(qw422016 *qt422016.Writer, prefix, link string) {
//line app/vmalert/web.qtpl:688
	qw422016.N().S(`
    <a class="btn details" target="_blank" title="Details" href="`)
//line app/vmalert/web.qtpl:689
	qw422016.E().S(prefix + link)
//line app/vmalert/web.qtpl:689
	qw422016.N().S(`">
        <svg height="16" width="16">
            <use href="`)
//line app/vmalert/web.qtpl:691
	qw422016.E().S(prefix)
//line app/vmalert/web.qtpl:691
	qw422016.N().S(`static/icons/icons.svg#details"/>
        </svg>
    </a>
`)
//line app/vmalert/web.qtpl:694
}

//line app/vmalert/web.qtpl:694
func writedetails(qq422016 qtio422016.Writer, prefix, link string) {
//line app/vmalert/web.qtpl:694
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vmalert/web.qtpl:694
	streamdetails(qw422016, prefix, link)
//line app/vmalert/web.qtpl:694
	qt422016.ReleaseWriter(qw422016)
//line app/vmalert/web.qtpl:694
}

//line app/vmalert/web.qtpl:694
func details(prefix, link string) string {
//line app/vmalert/web.qtpl:694
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vmalert/web.qtpl:694
	writedetails(qb422016, prefix, link)
//line app/vmalert/web.qtpl:694
	qs422016 := string(qb422016.B)
//line app/vmalert/web.qtpl:694
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vmalert/web.qtpl:694
	return qs422016
//line app/vmalert/web.qtpl:694
}
