include:
 - ../compose.yml
services:
  filebeat-victorialogs:
    image: docker.elastic.co/beats/filebeat:8.15.0
    restart: on-failure
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /var/lib/docker/containers/
        target: /var/lib/docker/containers/
      - ${PWD}/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    user: root
    command:
      - "--strict.perms=false"
    depends_on: [victorialogs]
