{
 "title": "VictoriaLogs - cluster (VM)",
 "description": "Overview for cluster version of VictoriaLogs v1.22.0 or higher",
 "tags": [
  "victoriametrics",
  "victorialogs"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(vm_app_version{version=~\"victoria-logs-.*\"}, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(vm_app_version{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(vm_app_version{job=~\"$job\", instance=~\"$instance\"},short_version)"
    }
   },
   { "name": "adhoc" },
   {
    "name": "instance_storage",
    "query": {
     "query": "label_values(vl_merges_total,instance)"
    }
   },
   {
    "name": "instance_insert",
    "query": {
     "query": "label_values(vlinsert_backend_conn_bytes_read_total,instance)"
    }
   },
   {
    "name": "instance_select",
    "query": {
     "query": "label_values(vlselect_backend_conn_reads_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total log entries",
     "type": "stat",
     "description": "Shows total amount of log entries in the storage.",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2400 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vl_storage_rows{job=~\"$job\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Ingested logs 24h",
     "type": "stat",
     "description": "The total number of log entries ingested over the past 24 hours.",
     "gridPos": { "h": 4, "w": 5, "x": 4, "y": 2400 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(vl_rows_ingested_total{job=~\"$job\", instance=~\"$instance\"}[24h]))"
      }
     ]
    },
    {
     "title": "Insert req/s",
     "type": "stat",
     "description": "Shows the average ingestion rate of log entries.",
     "gridPos": { "h": 4, "w": 5, "x": 9, "y": 2400 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(vl_rows_ingested_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Disk space usage",
     "type": "stat",
     "description": "Total amount of used disk space.\nAccounts for all compressed log entries and index size.\n\nSee how to [control disk usage](https://docs.victoriametrics.com/victorialogs/#retention-by-disk-space-usage).",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 2400 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vl_data_size_bytes{job=~\"$job\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Available CPU",
     "type": "stat",
     "description": "Integer number of CPU cores available to the application. This value is automatically rounded down from fractional CPU quotas since the Go runtime requires integer concurrency limits. Fractional CPU units should be avoided for optimal performance. See [best practices](https://docs.victoriametrics.com/victoriametrics/bestpractices/#kubernetes) documentation for more details.",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 2400 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vm_available_cpu_cores{job=~\"$job\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Version",
     "type": "text",
     "description": "See [latest releases](https://docs.victoriametrics.com/victorialogs/changelog/).",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2428 },
     "options": {
      "content": "<div style=\"text-align: center;\">$version</div>"
     }
    },
    {
     "title": "Ingested bytes 24h",
     "type": "stat",
     "description": "The cumulative number of log entries ingested over the last 24h. \n\nThe size is calculated before compression.",
     "gridPos": { "h": 4, "w": 5, "x": 4, "y": 2428 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(vl_bytes_ingested_total{job=~\"$job\", instance=~\"$instance\"}[24h]))"
      }
     ]
    },
    {
     "title": "Read req/s",
     "type": "stat",
     "description": "Shows the rate of HTTP read requests.",
     "gridPos": { "h": 4, "w": 5, "x": 9, "y": 2428 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(vl_http_requests_total{job=~\"$job\", instance=~\"$instance\", path=~\"/select/.*\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Compression ratio",
     "type": "stat",
     "description": "The ratio between original data size and compressed data stored on disk. This metric excludes indexdb size. \n\nThe ratio can go up or down as the system performs automatic maintenance and applies retention policies. For examples:\n- Background merges: [Merges](https://docs.victoriametrics.com/victorialogs/#forced-merge) improve compression by combining data into larger, more efficiently compressed blocks\n- Retention policies: When old data is deleted due to retention settings, the ratio changes as different time periods have varying compression characteristics\n\n",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 2428 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " sum(vl_uncompressed_data_size_bytes{job=~\"$job\", instance=~\"$instance\"}) / sum(vl_compressed_data_size_bytes{job=~\"$job\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Available memory",
     "type": "stat",
     "description": "Total system memory available to the application. This represents the system or container's memory capacity or limit, not the currently free memory.",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 2428 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vm_available_memory_bytes{job=~\"$job\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 2432 },
     "targets": [
      {
       "expr": "sum by (instance, version, tier) (\n  label_set(\n    vm_app_version{job=~\"$job\",instance=~\"$instance_select\"}\n      and on(instance,version)\n    vm_app_version{job=~\"$job\",instance=~\"$instance_insert\"} * 0 + 1,\n    \"tier\",\"select,insert\"\n  )\n\nor \n  label_set(\n    vm_app_version{job=~\"$job\",instance=~\"$instance_select\"}\n      unless on(instance,version)\n    vm_app_version{job=~\"$job\",instance=~\"$instance_insert\"} * 0 + 1,\n    \"tier\",\"select\"\n  )\n\nor\n  label_set(\n    vm_app_version{job=~\"$job\",instance=~\"$instance_insert\"}\n      unless on(instance,version)\n    vm_app_version{job=~\"$job\",instance=~\"$instance_select\"} * 0 + 1,\n    \"tier\",\"insert\"\n  )\n\nor\n  label_set(\n    vm_app_version{job=~\"$job\",instance=~\"$instance_storage\"} * 0 + 1,\n    \"tier\",\"storage\"\n  )\n)\n"
      }
     ]
    },
    {
     "title": "Uptime ($job)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 2432 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(min_over_time(up{job=~\"$job\", instance=~\"$instance_storage\"}[$__rate_interval]))",
       "legendFormat": "storage"
      },
      {
       "expr": "sum (\n  min_over_time(\n    up{job=~\"$job\", instance=~\"$instance_select\"}[$__rate_interval]\n  )\n  unless on(instance)\n  up{job=~\"$job\", instance=~\"$instance_insert\"}\n)",
       "legendFormat": "select"
      },
      {
       "expr": "sum (\n  min_over_time(\n    up{job=~\"$job\", instance=~\"$instance_insert\"}[$__rate_interval]\n  )\n  unless on(instance)\n  up{job=~\"$job\", instance=~\"$instance_select\"}\n)",
       "legendFormat": "insert"
      },
      {
       "expr": "sum(\n  min_over_time(\n    up{job=~\"$job\", instance=~\"$instance_select\"}[$__rate_interval]\n  )\n  and on(instance)\n  up{job=~\"$job\", instance=~\"$instance_insert\"}\n)",
       "legendFormat": "insert,select"
      }
     ]
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs ingestion rate ",
     "type": "timeseries",
     "description": "Shows ingestion rate in number of log entries and bytes per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2401 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vl_rows_ingested_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (type) > 0",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(rate(vl_bytes_ingested_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (type) > 0",
       "legendFormat": "{{type}} (bytes)"
      }
     ]
    },
    {
     "title": "Requests rate ",
     "type": "timeseries",
     "description": "* `*` - unsupported query path\n* `/insert` - [inserts](https://docs.victoriametrics.com/victorialogs/data-ingestion/)\n* `/select` - [reads](https://docs.victoriametrics.com/victorialogs/querying/)\n* `/metrics` - scraping of system metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2401 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vl_http_requests_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (path) > 0",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Requests error rate",
     "type": "timeseries",
     "description": "* `*` - unsupported query path\n* `/insert` - [inserts](https://docs.victoriametrics.com/victorialogs/data-ingestion/)\n* `/select` - [reads](https://docs.victoriametrics.com/victorialogs/querying/)\n* `/metrics` - scraping of system metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2409 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vm_http_request_errors_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (job, path) > 0",
       "legendFormat": "{{job}} - {{path}}"
      },
      {
       "expr": "sum(rate(vl_http_errors_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (job, path) > 0",
       "legendFormat": "{{job}} - {{path}}"
      }
     ]
    },
    {
     "title": "Query duration 0.99 quantile",
     "type": "timeseries",
     "description": "The less time it takes is better.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2409 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(vl_http_request_duration_seconds{job=~\"$job\", instance=~\"$instance\", quantile=\"0.99\"}) by (path) > 0",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Disk space usage ",
     "type": "timeseries",
     "description": "Shows the amount of on-disk space occupied by all the data stored in the storage.\n\nSee how to [control disk usage](https://docs.victoriametrics.com/victorialogs/#retention-by-disk-space-usage).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2417 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(vl_data_size_bytes{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "disk usage"
      }
     ]
    },
    {
     "title": "Logging rate",
     "type": "timeseries",
     "description": "Shows the rate of logging the messages by their level. Unexpected spike in rate is a good reason to check logs.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2417 },
     "targets": [
      {
       "expr": "sum(rate(vm_log_messages_total{job=~\"$job\", instance=~\"$instance\", level!=\"info\"}[$__rate_interval])) by (job, level, location) > 0",
       "legendFormat": "{{job}} - {{level}}: {{location}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Restarts",
     "type": "timeseries",
     "description": "Shows the number of restarts per job. The chart can be useful to identify periodic process restarts and correlate them with potential issues or anomalies. Normally, processes shouldn't restart unless restart was inited by user. The reason of restarts should be figured out by checking the logs of each specific service. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3172 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(changes(vm_app_start_timestamp{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) > 0) by(job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Log stream churn rate",
     "type": "timeseries",
     "description": "The number of the new [log streams](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields) created over the last 24h.\n\nPrefer having as low churn rate as possible. \nSee [How to determine which fields must be associated with log streams?](https://docs.victoriametrics.com/victorialogs/keyconcepts/#how-to-determine-which-fields-must-be-associated-with-log-streams)\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3172 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(vl_streams_created_total{job=~\"$job\", instance=~\"$instance\"}[1d])",
       "legendFormat": "new log streams over 24h"
      }
     ]
    },
    {
     "title": "Non-default flags",
     "type": "table",
     "description": "Flags explicitly set to non-default values",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3236 },
     "targets": [
      {
       "expr": "sum(flag{is_set=\"true\", job=~\"$job\", instance=~\"$instance\"}) by(job, instance, name, value)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logs dropped for last 1h",
     "type": "timeseries",
     "description": "Shows how many log entries were ignored or dropped on insertion due to various reasons:\n* timestamp out of retention period or timestamp in future;\n* number of fields per entry exceeded.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3236 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(vl_rows_dropped_total{job=~\"$job\", instance=~\"$instance\"}[1h])) by (job, reason)",
       "legendFormat": "{{job}} - {{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "RSS memory % usage ($instance)",
     "type": "timeseries",
     "description": "Percentage of used memory (resident).\nThe application's performance will significantly degrade when memory usage is close to 100%.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2779 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    max_over_time(process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n    /\n    vm_available_memory_bytes{job=~\"$job\", instance=~\"$instance\"}\n) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU % usage ($instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2779 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n    /\n    process_cpu_cores_available{job=~\"$job\", instance=~\"$instance\"}\n) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RSS anonymous memory % usage ($instance)",
     "type": "timeseries",
     "description": "Share for memory allocated by the process itself. When memory usage reaches 100% it will be likely OOM-killed.\nSafe memory usage % considered to be below 80%",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2787 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    max_over_time(process_resident_memory_anon_bytes{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n    /\n    vm_available_memory_bytes{job=~\"$job\", instance=~\"$instance\"}\n) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU pressure",
     "type": "timeseries",
     "description": "Shows CPU pressure based on [Pressure Stall Information](https://docs.kernel.org/accounting/psi.html).\n\nThe lower the better.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2787 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(rate(process_pressure_cpu_waiting_seconds_total{job=~\"$job\"}[$__rate_interval])) by (job)",
       "legendFormat": "{{job}} - waiting"
      },
      {
       "expr": "max(rate(process_pressure_cpu_stalled_seconds_total{job=~\"$job\"}[$__rate_interval])) by (job)",
       "legendFormat": "{{job}} - stalled"
      }
     ]
    },
    {
     "title": "Memory pressure",
     "type": "timeseries",
     "description": "Shows memory pressure based on [Pressure Stall Information](https://docs.kernel.org/accounting/psi.html).\n\nThe lower the better.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2795 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(rate(process_pressure_memory_waiting_seconds_total{job=~\"$job\"}[$__rate_interval])) by (job)",
       "legendFormat": "{{job}} - waiting"
      },
      {
       "expr": "max(rate(process_pressure_memory_stalled_seconds_total{job=~\"$job\"}[$__rate_interval])) by (job)",
       "legendFormat": "{{job}} - stalled"
      }
     ]
    },
    {
     "title": "Disk writes/reads ($instance)",
     "type": "timeseries",
     "description": "Shows the number of bytes read/write from the storage layer.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2795 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(process_io_storage_read_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job) > 0",
       "legendFormat": "read {{job}}"
      },
      {
       "expr": "sum(rate(process_io_storage_written_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job) > 0",
       "legendFormat": "write {{job}}"
      }
     ]
    },
    {
     "title": "Open FDs ($instance)",
     "type": "timeseries",
     "description": "Shows the percentage of open file descriptors compared to the limit set in the OS.\nReaching the limit of open files can cause various issues and must be prevented.\n\nSee how to change limits here https://medium.com/@muhammadtriwibowo/set-permanently-ulimit-n-open-files-in-ubuntu-4d61064429a",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2803 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    max_over_time(process_open_fds{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n    /\n    process_max_fds{job=~\"$job\", instance=~\"$instance\"}\n) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk write/read calls ($instance)",
     "type": "timeseries",
     "description": "Shows the number of read/write syscalls such as read, pread, write, pwrite.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2803 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(process_io_read_syscalls_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job) > 0",
       "legendFormat": "read {{job}}"
      },
      {
       "expr": "sum(rate(process_io_write_syscalls_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job) > 0",
       "legendFormat": "write {{job}}"
      }
     ]
    },
    {
     "title": "Goroutines ($instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2811 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(max_over_time(go_goroutines{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "IO pressure",
     "type": "timeseries",
     "description": "Shows IO pressure based on [Pressure Stall Information](https://docs.kernel.org/accounting/psi.html).\n\nThe lower the better.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2811 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(rate(process_pressure_io_waiting_seconds_total{job=~\"$job\"}[$__rate_interval])) by (job)",
       "legendFormat": "{{job}} - waiting"
      },
      {
       "expr": "max(rate(process_pressure_io_stalled_seconds_total{job=~\"$job\"}[$__rate_interval])) by (job)",
       "legendFormat": "{{job}} - stalled"
      }
     ]
    },
    {
     "title": "Threads ($instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2819 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(max_over_time(process_num_threads{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP connections ($instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2819 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(max_over_time(vm_tcplistener_conns{job=~\"$job\", instance=~\"$instance\"}[$__interval])) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU spent on GC ($instance)",
     "type": "timeseries",
     "description": "Shows the percent of CPU spent on garbage collection.\n\nIf % is high, then CPU usage can be decreased by changing GOGC to higher values. Increasing GOGC value will increase memory usage, and decrease CPU usage.\n\nTry searching for keyword `GOGC` at https://docs.victoriametrics.com/victoriametrics/troubleshooting/ ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2827 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n  rate(go_gc_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) \n / rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n ) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP connections rate ($instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2827 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vm_tcplistener_accepts_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory allocations rate",
     "type": "timeseries",
     "description": "Shows the rate of allocations in memory. Sudden increase in allocations would mean increased pressure on Go Garbage Collector and can saturate CPU resources of the application.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2835 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(rate(go_memstats_alloc_bytes_total{job=~\"$job\"}[$__rate_interval])) by (job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Go scheduling latency",
     "type": "timeseries",
     "description": "Shows the time goroutines have spent in runnable state before actually running. The lower is better.\n\nHigh values or values exceeding the threshold is usually a sign of            insufficient CPU resources or CPU throttling. \n\nVerify that service has enough CPU resources. Otherwise, the service could work unreliably with delays in processing.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2835 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(histogram_quantile(0.99, sum(rate(go_sched_latencies_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (job, instance, le))) by(job)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores ($instance)",
     "type": "timeseries",
     "description": "- user: total CPU time spent in user space (app code)\n- system: total CPU time spent in system/kernel space (e.g., syscalls)\n- total: user + system\n\nIf system CPU rises while user % falls, suspect: disk bottlenecks, memory pressure and high GC overhead",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(process_cpu_cores_available{job=~\"$job\", instance=~\"$instance_storage\"})",
       "legendFormat": "Limit"
      },
      {
       "expr": "sum(rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance_storage\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Physical memory usage ($instance_storage)",
     "type": "timeseries",
     "description": "How much memory (RAM) the VictoriaLogs process is actually using, compared to its allowed container or system limit. See 'Memory Usage' panel for a detailed breakdown.\n\n- Good: Below 70% most of the time, maybe spiking a bit under load.\n- Bad: Above 90% for more than 5 minutes = risk of out-of-memory (OOM) kill.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance_storage\"}[$__rate_interval]) by (instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(vm_available_memory_bytes{job=~\"$job\", instance=~\"$instance_storage\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Partition Count (sum of $instance_storage)",
     "type": "stat",
     "description": "Shows the total number of time-based (daily) partitions in storage. The number typically grows over time as new data arrives and is partitioned by time periods. \n\nExcessive partition counts may indicate retention policy issues or very high data ingestion rates that could impact query performance.",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vl_partitions{job=~\"$job\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Disk ($instance_storage)",
     "type": "timeseries",
     "description": "Shows disk space usage and limits for VictoriaLogs storage. Tracks current data usage against the configured retention limit or available disk space.\n\nThe red line indicates the space retention limit. When usage approaches this limit, older data will be automatically deleted. If the space retention limit (`-retention.maxDiskSpaceUsageBytes`) is not specified, the red line represents the maximum disk space. In that case, the storage will switch to read-only mode when the limit is reached.",
     "gridPos": { "h": 8, "w": 9, "x": 3, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(vl_max_disk_space_usage_bytes{job=~\"$job\", instance=~\"$instance_storage\"}) OR (max(vl_free_disk_space_bytes{job=~\"$job\", instance=~\"$instance_storage\"} + vl_data_size_bytes{job=~\"$job\", instance=~\"$instance_storage\"}))",
       "legendFormat": "max space retention/ limit"
      },
      {
       "expr": "sum(vl_data_size_bytes{job=~\"$job\", instance=~\"$instance_storage\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "HTTP request rate ($instance_storage)",
     "type": "timeseries",
     "description": "Shows the rate of incoming query requests by endpoint path. This metric tracks the query load on VictoriaLogs, including different query interfaces and internal operations. \n\nHigher rates indicate increased query activity from users or applications. Monitor for sudden spikes that might indicate new dashboards, automated queries, or potential performance issues. Sustained high rates may require scaling query processing capacity.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vl_http_requests_total{job=~\"$job\", instance=~\"$instance_storage\"}[$__rate_interval])) by (path) > 0",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "HTTP request duration 0.99 quantile (sum of $instance_storage)",
     "type": "timeseries",
     "description": "Shows the 99th percentile of HTTP request duration. This represents the time it takes for 99% of HTTP operations to complete. High values indicate slow ingestion/querying performance that could affect overall system throughput. Spikes may suggest storage bottlenecks, resource contention, or inefficient data processing.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(vl_http_request_duration_seconds{job=~\"$job\", instance=~\"$instance_storage\", quantile=\"0.99\"}) by (path) > 0",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Logs ingestion rate ",
     "type": "timeseries",
     "description": "Shows ingestion rate in number of log entries and bytes per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vl_rows_ingested_total{job=~\"$job\", instance=~\"$instance_storage\"}[$__rate_interval])) by (type) > 0",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(rate(vl_bytes_ingested_total{job=~\"$job\", instance=~\"$instance_storage\"}[$__rate_interval])) by (type) > 0",
       "legendFormat": "{{type}} (bytes)"
      }
     ]
    },
    {
     "title": "Concurrent inserts (max of $instance)",
     "type": "timeseries",
     "description": "Shows the number of concurrent insert operations compared to the configured limit. \n\nHigh utilization near the limit may indicate ingestion bottlenecks. If current consistently approaches the limit, consider increasing the concurrency limit or optimizing ingestion performance. Sustained saturation can lead to insert request queuing and increased latency.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(max_over_time(vm_concurrent_insert_current{job=~\"$job\", instance=~\"$instance_storage\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "max(vm_concurrent_insert_capacity{job=~\"$job\", instance=~\"$instance_storage\"}[$__rate_interval])",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Pending rows (sum of $instance_storage)",
     "type": "timeseries",
     "description": "Shows the number of log rows waiting to be written to storage, categorized by type. Pending rows indicate temporary queuing during ingestion. Consistently high values may suggest storage write bottlenecks or insufficient write capacity.\n\nPending rows are flushed in two ways:\n\n- After a specific time period (typically 1 second)\n- When the pending row size exceeds a threshold (typically 1.75 MB)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(vl_pending_rows{job=~\"$job\", instance=~\"$instance_storage\"}[$__rate_interval]) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Message processors ($instance_storage)",
     "type": "timeseries",
     "description": "Displays the number of active message processors handling log ingestion. These processors parse and process incoming log messages before storage. The count typically correlates with the ingestion load.\n\nIf this number is unusually high or inflated (which is rare), check memory usage. It may indicate a heavy ingestion load or processing bottlenecks that could benefit from performance tuning.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(vl_insert_processors_count{job=~\"$job\", instance=~\"$instance_storage\"}[$__rate_interval]) by (instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "max(vm_concurrent_insert_capacity{job=~\"$job\", instance=~\"$instance_storage\"}[$__rate_interval])",
       "legendFormat": "soft limit"
      }
     ]
    },
    {
     "title": "Streams churn rate 24h ($instance_storage)",
     "type": "timeseries",
     "description": "The number of new [log streams](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields) created over the last 24 hours. Lower is better. See [How to determine which fields must be associated with log streams?](https://docs.victoriametrics.com/victorialogs/keyconcepts/#how-to-determine-which-fields-must-be-associated-with-log-streams)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(vl_streams_created_total{job=~\"$job\", instance=~\"$instance_storage\"}[1d])) by (instance)",
       "legendFormat": "{{instace}}"
      }
     ]
    },
    {
     "title": "Query duration 0.99 quantile (max of $instance_storage))",
     "type": "timeseries",
     "description": "Shows the 99th percentile of query execution duration. This represents the time it takes for 99% of queries to complete:\n\n- High values indicate slow query performance that affects user experience. \n- Spikes may suggest complex queries, resource contention, or inefficient indexes. Monitor for trends that could indicate degrading performance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(vl_http_request_duration_seconds{job=~\"$job\", instance=~\"$instance_storage\", quantile=\"0.99\", path=~\"^/(internal/)?select.*\"}) by (path) > 0",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Flush duration 0.99 quantile (max of $instance_storage)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(vl_insert_flush_duration_seconds{job=~\"$job\", instance=~\"$instance_storage\", quantile=\"0.99\"}) by (type) > 0",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Rows read/query 0.99 quantile (sum of $instance_storage)",
     "type": "timeseries",
     "description": "Shows the 99th percentile of log rows read per query. This metric indicates query scan efficiency and data volume processed. \n\nHigh values may suggest broad queries that scan large amounts of data, potentially impacting performance. Consider adding filters, time ranges, or optimizing query patterns if values are consistently high.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(histogram_quantile(0.99, sum(rate(vl_storage_rows_read_per_query_bucket{job=~\"$job\", instance=~\"$instance_storage\"}[$__rate_interval])) by (vmrange)))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Query requests rate (sum of $instance_storage)",
     "type": "timeseries",
     "description": "Shows the rate of incoming query requests by endpoint path. This metric tracks the query load on VictoriaLogs, including different query interfaces and internal operations. \n\nHigher rates indicate increased query activity from users or applications. Monitor for sudden spikes that might indicate new dashboards, automated queries, or potential performance issues. Sustained high rates may require scaling query processing capacity.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vl_http_requests_total{job=~\"$job\", instance=~\"$instance_storage\",path=~\"^/(internal/)?select.*\"}[$__rate_interval])) by (path) > 0",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Query request duration 0.99 quantile ($instance_storage)",
     "type": "timeseries",
     "description": "Shows the 99th percentile of query execution duration. This represents the time it takes for 99% of queries to complete:\n\n- High values indicate slow query performance that affects user experience. \n- Spikes may suggest complex queries, resource contention, or inefficient indexes. Monitor for trends that could indicate degrading performance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(vl_http_request_duration_seconds{job=~\"$job\",instance=~\"$instance_storage\",quantile=\"0.99\",path=~\"^/(internal/)?select.*\"}) by (path) > 0",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Used streams/query 0.99 quantile (max of $instance_storage)",
     "type": "timeseries",
     "description": "Shows the 99th percentile of log streams accessed per query. The higher, the better.\n\nThis panel answers the question: \"How many streams did your query use to fetch logs?\" Using a [stream filter](https://docs.victoriametrics.com/victorialogs/logsql/#stream-filter) is one of the most common and efficient ways to fetch logs.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(histogram_quantile(0.99, sum(rate(vl_storage_streams_used_per_query_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (instance, vmrange)))",
       "legendFormat": "streams"
      }
     ]
    },
    {
     "title": "Part count (sum of $instance)",
     "type": "timeseries",
     "description": "Shows the number of ongoing merge operations by storage type. Smaller parts are continuously merged into larger ones for optimization. \n\nActive merges are normal background operations that improve query performance and storage efficiency. High numbers of active merges for 'storage/inmemory', 'storage/small' types are expected, while sustained high activity might indicate heavy write load or storage optimization in progress.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(vl_storage_parts{job=~\"$job\", instance=~\"$instance_storage\"}) by(type)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bytes read/query 0.99 quantile (sum of $instance_storage)",
     "type": "timeseries",
     "description": "Shows the 99th percentile of bytes read per query. This metric indicates the amount of data processed during queries and correlates with query performance.\n\n- If the number of rows read is high but the bytes read is low, the query is efficient.\n- High byte values may indicate queries scanning large amounts of data, potentially affecting performance and resource usage. Consider optimizing queries using more specific filters (e.g., [stream filter](https://docs.victoriametrics.com/victorialogs/logsql/#stream-filter), only necessary rows) or narrower time ranges to reduce data volume.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(histogram_quantile(0.99, sum(rate(vl_storage_bytes_read_per_query_bucket{job=~\"$job\", instance=~\"$instance_storage\"}[$__rate_interval])) by (vmrange)))",
       "legendFormat": "rows"
      }
     ]
    },
    {
     "title": "Merge duration 0.99 percentile (max of $instance_storage)",
     "type": "timeseries",
     "description": "Shows the 99th percentile duration of merge operations by storage type. Merge operations combine smaller storage parts into larger ones for optimization. \n\nNormal merge durations vary by storage type and data volume. Consistently high durations may indicate storage performance issues, high write load, or insufficient resources for background operations. Monitor for trends that could impact overall system performance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(vl_merge_duration_seconds{job=~\"$job\", instance=~\"$instance\", quantile=\"0.99\"}) by (type) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Merge bytes 0.99 percentile (max of $instance_storage)",
     "type": "timeseries",
     "description": "Shows the 99th percentile of data volume processed during merge operations by storage type. \n\nThis metric indicates the scale of background storage optimization activities. Larger merge sizes generally improve storage efficiency but require more resources. Consistently high values may indicate heavy write loads or large storage parts that need optimization. Monitor correlation with merge duration for performance insights.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(vl_merge_bytes{job=~\"$job\", instance=~\"$instance\", quantile=\"0.99\"}) by (type) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Merge events (sum of $instance_storage)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(vl_merges_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(type)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Insert",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage ($instance_insert)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(process_cpu_cores_available{job=~\"$job\", instance=~\"$instance_insert\"})",
       "legendFormat": "Limit"
      },
      {
       "expr": "sum(rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance_insert\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Physical memory usage ($instance_insert)",
     "type": "timeseries",
     "description": "How much memory (RAM) the VictoriaLogs process is actually using, compared to its allowed container or system limit. See 'Memory Usage' panel for a detailed breakdown.\n\n- Good: Below 70% most of the time, maybe spiking a bit under load.\n- Bad: Above 90% for more than 5 minutes = risk of out-of-memory (OOM) kill.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance_insert\"}[$__rate_interval]) by (instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(vm_available_memory_bytes{job=~\"$job\", instance=~\"$instance_insert\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "HTTP request rate ($instance_storage)",
     "type": "timeseries",
     "description": "Shows the rate of incoming query requests by endpoint path. This metric tracks the query load on VictoriaLogs, including different query interfaces and internal operations. \n\nHigher rates indicate increased query activity from users or applications. Monitor for sudden spikes that might indicate new dashboards, automated queries, or potential performance issues. Sustained high rates may require scaling query processing capacity.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vl_http_requests_total{job=~\"$job\", instance=~\"$instance_insert\"}[$__rate_interval])) by (path) > 0",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "HTTP request duration 0.99 quantile (sum of $instance_insert)",
     "type": "timeseries",
     "description": "Shows the 99th percentile of insert operation duration. This represents the time it takes for 99% of insert operations to complete. High values indicate slow ingestion performance that could affect overall system throughput. Spikes may suggest storage bottlenecks, resource contention, or inefficient data processing.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(vl_http_request_duration_seconds{job=~\"$job\", instance=~\"$instance_insert\", quantile=\"0.99\"}) by (path) > 0",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Logs ingestion rate ",
     "type": "timeseries",
     "description": "Shows ingestion rate in number of log entries and bytes per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vl_rows_ingested_total{job=~\"$job\", instance=~\"$instance_insert\"}[$__rate_interval])) by (type) > 0",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(rate(vl_bytes_ingested_total{job=~\"$job\", instance=~\"$instance_insert\"}[$__rate_interval])) by (type) > 0",
       "legendFormat": "{{type}} (bytes)"
      }
     ]
    },
    {
     "title": "Message processors ($instance_insert)",
     "type": "timeseries",
     "description": "Displays the number of active message processors handling log ingestion. These processors parse and process incoming log messages before storage. The count typically correlates with the ingestion load.\n\nIf this number is unusually high or inflated (which is rare), check memory usage. It may indicate a heavy ingestion load or processing bottlenecks that could benefit from performance tuning.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(vl_insert_processors_count{job=~\"$job\", instance=~\"$instance_insert\"}[$__rate_interval]) by (instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "max(vm_concurrent_insert_capacity{job=~\"$job\", instance=~\"$instance_insert\"}[$__rate_interval])",
       "legendFormat": "soft limit"
      }
     ]
    },
    {
     "title": "Concurrent inserts ($instance)",
     "type": "timeseries",
     "description": "Shows the number of concurrent insert operations compared to the configured limit. \n\nHigh utilization near the limit may indicate ingestion bottlenecks. If current consistently approaches the limit, consider increasing the concurrency limit or optimizing ingestion performance. Sustained saturation can lead to insert request queuing and increased latency.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(max_over_time(vm_concurrent_insert_current{job=~\"$job\", instance=~\"$instance_insert\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "max(vm_concurrent_insert_capacity{job=~\"$job\", instance=~\"$instance_insert\"}[$__rate_interval])",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Flush duration 0.99 quantile (max of $instance_insert)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(vl_insert_flush_duration_seconds{job=~\"$job\", instance=~\"$instance_insert\", quantile=\"0.99\"}) by (type) > 0",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Tracked streams ($instance_insert)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(vl_insert_active_streams{job=~\"$job\", instance=~\"$instance_insert\"}) by (instance) > 0",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Send errors over 24h ($instance_insert)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(vl_insert_remote_send_errors_total{job=~\"$job\", instance=~\"$instance_insert\"}[24h])) by (instance) > 0",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Select",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage ($instance_select)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(process_cpu_cores_available{job=~\"$job\", instance=~\"$instance_select\"})",
       "legendFormat": "Limit"
      },
      {
       "expr": "sum(rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance_select\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Physical memory usage ($instance_select)",
     "type": "timeseries",
     "description": "How much memory (RAM) the VictoriaLogs process is actually using, compared to its allowed container or system limit. See 'Memory Usage' panel for a detailed breakdown.\n\n- Good: Below 70% most of the time, maybe spiking a bit under load.\n- Bad: Above 90% for more than 5 minutes = risk of out-of-memory (OOM) kill.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance_select\"}[$__rate_interval]) by (instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(vm_available_memory_bytes{job=~\"$job\", instance=~\"$instance_select\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "HTTP request rate ($instance_select)",
     "type": "timeseries",
     "description": "Shows the rate of incoming query requests by endpoint path. This metric tracks the query load on VictoriaLogs, including different query interfaces and internal operations. \n\nHigher rates indicate increased query activity from users or applications. Monitor for sudden spikes that might indicate new dashboards, automated queries, or potential performance issues. Sustained high rates may require scaling query processing capacity.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vl_http_requests_total{job=~\"$job\", instance=~\"$instance_select\"}[$__rate_interval])) by (path) > 0",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "HTTP request duration 0.99 quantile ($instance_select)",
     "type": "timeseries",
     "description": "Shows the 99th percentile of query execution duration. This represents the time it takes for 99% of queries to complete:\n\n- High values indicate slow query performance that affects user experience. \n- Spikes may suggest complex queries, resource contention, or inefficient indexes. Monitor for trends that could indicate degrading performance.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(vl_http_request_duration_seconds{job=~\"$job\", instance=~\"$instance_select\", quantile=\"0.99\"}) by (path) > 0",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Concurrent queries ($instance)",
     "type": "timeseries",
     "description": "Shows the number of concurrent select (query) operations compared to the configured limit.\n\nHigh utilization near the limit may indicate query bottlenecks or insufficient query processing capacity.\n\nIf it's consistently high while CPU usage remains low, consider increasing the concurrency limit (`-search.maxConcurrentRequests`) or optimizing query performance to support more concurrent users.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(max_over_time(vl_concurrent_select_current{job=~\"$job\", instance=~\"$instance_select\"}[$__rate_interval]))",
       "legendFormat": "current"
      },
      {
       "expr": "max(vl_concurrent_select_capacity{job=~\"$job\", instance=~\"$instance_select\"}[$__rate_interval])",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Send errors over 24h ($instance_select)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(vl_select_remote_send_errors_total{job=~\"$job\", instance=~\"$instance_select\"}[24h])) by (instance) > 0",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  }
 ]
}