{
 "title": "Node Exporter - vmanomaly",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   {
    "name": "cpu_mode",
    "label": "cpu_mode",
    "query": {
     "query": "label_values(anomaly_score{for=\"cpu_seconds_total\"},mode)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Percentage of Anomalous Nodes",
   "type": "timeseries",
   "description": "- if not filtered, shows global percentage of anomalies\n-if filtered by Node, shows % of anomalous indicators",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "count((min(anomaly_score{preset=\"node-exporter\",instance=~\"$node\"}) by (for, instance))>1)/count((min(anomaly_score{preset=\"node-exporter\",instance=~\"$node\"}) by (for, instance)))",
     "legendFormat": "Percentage"
    }
   ]
  },
  {
   "title": "Anomalies per Indicator",
   "type": "state-timeline",
   "description": "Count of anomaly scores greater than threshold",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "WITH(f={preset=\"node-exporter\"}) count(count(min(anomaly_score{f}) without (model_alias,scheduler_alias)>=1.0) by (for)) by (for)/count(count by (for) (anomaly_score{f})) by (for)",
     "legendFormat": "{{for}}"
    }
   ]
  },
  {
   "title": "Numbers of Anomalous Indicators by Node",
   "type": "timeseries",
   "description": "Number of anomalous indicators per node",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "count((min(anomaly_score{preset=\"node-exporter\",instance=~\"$node\"}) without (model_alias,scheduler_alias))>=1.0) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Anomalies: Network Receive Bytes",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "WITH(f={instance=~\"$node\",for=\"receive_bytes\",preset=\"node-exporter\"}) count(min(anomaly_score{f}) without (model_alias,scheduler_alias)>=1.0) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic- Receive Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])*8",
     "legendFormat": "{{instance}},{{device}}"
    }
   ]
  },
  {
   "title": "Anomalies: Network Transmit Bytes",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "WITH(f={instance=~\"$node\",for=\"transmit_bytes\",preset=\"node-exporter\"}) count(min(anomaly_score{f}) without (model_alias,scheduler_alias)>=1.0) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic - Transmit Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])*8",
     "legendFormat": "{{instance}},{{device}}"
    }
   ]
  },
  {
   "title": "CPU seconds",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "options": {
    "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  {
   "title": "CPU seconds. Mode: $cpu_mode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "repeat": "cpu_mode",
   "collapsed": true,
   "panels": [
    {
     "title": "Anomalies: CPU Seconds: Mode $cpu_mode",
     "type": "state-timeline",
     "description": "Sudden spike of Node CPU seconds",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "WITH(f={instance=~\"$node\",for=\"cpu_seconds_total\",preset=\"node-exporter\",mode=~\"$cpu_mode\"}) count(min(anomaly_score{f}) without (model_alias,scheduler_alias)>=1.0) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Basic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\", mode=~\"$cpu_mode\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Storage disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Latency",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "options": {
    "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  {
   "title": "Anomalies: Read Latency",
   "type": "state-timeline",
   "description": "Sudden drop or spike of Read latency",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "WITH(f={instance=~\"$node\",for=\"read_latency\",preset=\"node-exporter\"}) count(min(anomaly_score{f}) without (model_alias,scheduler_alias)>=1.0) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Average Wait Time: Read",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\",job=~\"$job\"}[$__rate_interval]) / irate(node_disk_reads_completed_total{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}},{{device}}"
    }
   ]
  },
  {
   "title": "Anomalies: Write Latency",
   "type": "state-timeline",
   "description": "Sudden drop or spike of Write latency",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "WITH(f={instance=~\"$node\",for=\"write_latency\",preset=\"node-exporter\"}) count(min(anomaly_score{f}) without (model_alias,scheduler_alias)>=1.0) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Average Wait Time: Write",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\",job=~\"$job\"}[$__rate_interval]) / irate(node_disk_writes_completed_total{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}},{{device}}"
    }
   ]
  },
  { "title": "System Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Anomalies: Context Switch",
   "type": "state-timeline",
   "description": "Sudden spike of Context Switch",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "WITH(f={for=\"context_switch\",preset=\"node-exporter\",instance=~\"$node\",job=~\"$job\"}) count(min(anomaly_score{f}) without (model_alias,scheduler_alias)>=1.0) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Anomalies: Host Network Transmit Errors",
   "type": "state-timeline",
   "description": "Sudden drop or spike of Host Network Transmit Errors",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "WITH(f={for=\"host_network_transmit_errors\",preset=\"node-exporter\",instance=~\"$node\",job=~\"$job\"}) count(min(anomaly_score{f}) without (model_alias,scheduler_alias)>=1.0) by (instance)",
     "legendFormat": "Value - {{instance}}"
    }
   ]
  },
  {
   "title": "Network Receive Traffic Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}},{{device}}"
    }
   ]
  },
  {
   "title": "Anomalies: Host Network Receive Errors",
   "type": "state-timeline",
   "description": "Sudden drop or spike of Host Network Receive Errors",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "WITH(f={for=\"host_network_receive_errors\",preset=\"node-exporter\",instance=~\"$node\",job=~\"$job\"}) count(min(anomaly_score{f}) without (model_alias,scheduler_alias)>=1.0) by (instance)",
     "legendFormat": "Value - {{instance}}"
    }
   ]
  },
  {
   "title": "Network Transmit Traffic Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_errs_total{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}},{{device}}"
    }
   ]
  }
 ]
}