// Code generated by qtc from "footer.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line app/vmalert/tpl/footer.qtpl:1
package tpl

//line app/vmalert/tpl/footer.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line app/vmalert/tpl/footer.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line app/vmalert/tpl/footer.qtpl:1
func StreamFooter(qw422016 *qt422016.Writer) {
//line app/vmalert/tpl/footer.qtpl:1
	qw422016.N().S(`
        </main>
        <script src="/static/js/jquery-3.6.0.min.js" type="text/javascript"></script>
        <script src="/static/js/bootstrap.bundle.min.js" type="text/javascript"></script>
        <script type="text/javascript">
            function expandAll() {
               $('.collapse').addClass('show');
            }
            function collapseAll() {
               $('.collapse').removeClass('show');
            }

            $(document).ready(function() {
              // prevent collapse logic on link click
              $(".group-heading a").click(function(e) {
                e.stopPropagation();
              });

              $(".group-heading").click(function(e) {
                 let target = $(this).attr('data-bs-target');
                 let el = $("#"+target);
                  new bootstrap.Collapse(el, {
                    toggle: true
                  });
              });

              var hash = window.location.hash.substr(1);
              let group = $("#"+hash);
              if (group.length > 0) {
                group.click();
              }
            });
        </script>
    </body>
</html>
`)
//line app/vmalert/tpl/footer.qtpl:36
}

//line app/vmalert/tpl/footer.qtpl:36
func WriteFooter(qq422016 qtio422016.Writer) {
//line app/vmalert/tpl/footer.qtpl:36
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vmalert/tpl/footer.qtpl:36
	StreamFooter(qw422016)
//line app/vmalert/tpl/footer.qtpl:36
	qt422016.ReleaseWriter(qw422016)
//line app/vmalert/tpl/footer.qtpl:36
}

//line app/vmalert/tpl/footer.qtpl:36
func Footer() string {
//line app/vmalert/tpl/footer.qtpl:36
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vmalert/tpl/footer.qtpl:36
	WriteFooter(qb422016)
//line app/vmalert/tpl/footer.qtpl:36
	qs422016 := string(qb422016.B)
//line app/vmalert/tpl/footer.qtpl:36
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vmalert/tpl/footer.qtpl:36
	return qs422016
//line app/vmalert/tpl/footer.qtpl:36
}
