services:
  grafana:
    container_name: grafana
    image: grafana/grafana:11.5.0
    depends_on:
      - "vmauth"
    ports:
      - 3000:3000
    volumes:
      - grafanadata:/var/lib/grafana
      - ./provisioning/datasources/victoriametrics-metrics-datasource/cluster.yml:/etc/grafana/provisioning/datasources/cluster.yml
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./../../dashboards/vm/victoriametrics-cluster.json:/var/lib/grafana/dashboards/vm.json
      - ./../../dashboards/vm/vmagent.json:/var/lib/grafana/dashboards/vmagent.json
      - ./../../dashboards/vm/vmalert.json:/var/lib/grafana/dashboards/vmalert.json
      - ./../../dashboards/vm/vmauth.json:/var/lib/grafana/dashboards/vmauth.json
    environment:
      - "GF_INSTALL_PLUGINS=victoriametrics-metrics-datasource"
    restart: always
