services:
  fluentbit:
    image: cr.fluentbit.io/fluent/fluent-bit:3.0.7
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on: [victorialogs-1,victorialogs-2]
    ports:
      - "5140:5140"

  victorialogs-1:
    image: docker.io/victoriametrics/victoria-logs:v0.29.0-victorialogs
    volumes:
      - victorialogs-fluentbit-vl-ha-single-1:/vlogs
    command:
      - -storageDataPath=/vlogs
  victorialogs-2:
    image: docker.io/victoriametrics/victoria-logs:v0.29.0-victorialogs
    volumes:
      - victorialogs-fluentbit-vl-ha-single-2:/vlogs
    command:
      - -storageDataPath=/vlogs
  vmauth:
    container_name: vmauth
    image: victoriametrics/vmauth:v1.103.0
    depends_on:
      - "victorialogs-1"
      - "victorialogs-2"
    volumes:
      - ./auth.yml:/etc/auth.yml
    command:
      - '--auth.config=/etc/auth.yml'
    ports:
      - 8427:8427
    restart: always
volumes:
  victorialogs-fluentbit-vl-ha-single-1:
  victorialogs-fluentbit-vl-ha-single-2:
