version: "3.5"
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:9.2.7
    depends_on:
      - "victoriametrics"
    ports:
      - 3000:3000
    volumes:
      - grafanadata:/var/lib/grafana
      - ./provisioning/datasources/victoriametrics-datasource:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./provisioning/plugins/:/var/lib/grafana/plugins
      - ./../../dashboards/vm/victoriametrics.json:/var/lib/grafana/dashboards/vm.json
      - ./../../dashboards/vm/vmagent.json:/var/lib/grafana/dashboards/vmagent.json
      - ./../../dashboards/vm/vmalert.json:/var/lib/grafana/dashboards/vmalert.json
    environment:
      - "VM_DS_VER=${VM_DS_VER}"
      - "GF_ALLOW_LOADING_UNSIGNED_PLUGINS=victoriametrics-datasource"
      - "GF_DEFAULT_APP_MODE=development"
    networks:
      - vm_net
    restart: always
