global:
  scrape_interval: 10s

scrape_configs:
  - job_name: victoriametrics
    static_configs:
      - targets:
          - victoriametrics:8428
  - job_name: victoriatraces
    static_configs:
      - targets:
          - victoriatraces:9428