global:
  scrape_interval: 10s

scrape_configs:
- job_name: victoriametrics
  static_configs:
  - targets:
    - victoriametrics:8428
- job_name: vmalert
  static_configs:
  - targets:
    - vmalert:8880
- job_name: vlstorage
  static_configs:
  - targets:
    - vlstorage-1:9428
    - vlstorage-2:9428
- job_name: vlselect
  static_configs:
  - targets:
    - vlselect-1:9428
    - vlselect-2:9428
- job_name: vlinsert
  static_configs:
  - targets:
    - vlinsert:9428
