global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']
  - job_name: 'victorialogs'
    static_configs:
      - targets: ['victorialogs:9428']
  - job_name: 'fluentbit'
    static_configs:
      - targets: ['fluentbit:2020/api/v1/metrics/prometheus']