groups:
  - name: log-rules
    type: vlogs
    interval: 30s
    rules:
      - alert: AlwaysFiring
        expr: '* | stats count()'
        annotations:
          description: "Generated more than {{$value}} log entries in the last 1 minute"
      - alert: TooManyLogs
        expr: '* | stats by (path) count() as total | filter total:>50'
        annotations:
          description: "Path {{$labels.path}} generated more than 50 log entries in the last 1 minute: {{$value}}"
      - record: path:logs:count
        expr: '* | stats by (path) count()'
