apiVersion: 1

datasources:
    - name: VictoriaMetrics - cluster
      type: prometheus
      access: proxy
      url: http://vmauth:8427/select/0/prometheus
      isDefault: true
      # Basic Auth credentials for the datasource
      # This is used to authenticate with the vmauth service
      # Note: please check changes in the vmauth configuration `auth-vm-cluster.yml`
      # to ensure the credential match
      basicAuth: true
      basicAuthUser: foo
      secureJsonData:
        basicAuthPassword: bar
      jsonData:
        prometheusType: Prometheus
        prometheusVersion: 2.24.0
