services:
  collector:
    image: docker.io/otel/opentelemetry-collector-contrib:0.102.1
    restart: on-failure
    volumes:
      - $PWD/logs:/tmp/logs
      - $PWD/config.yaml:/etc/otelcol-contrib/config.yaml
    depends_on:
      victorialogs:
        condition: service_healthy
      victoriametrics:
        condition: service_healthy

  victorialogs:
    image: docker.io/victoriametrics/victoria-logs:v0.28.0-victorialogs
    volumes:
      - victorialogs-vector-docker-vl:/loki
    ports:
      - '9428:9428'
    command:
      - -storageDataPath=/loki
      - -loggerFormat=json
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:9428/health"]
      interval: 1s
      timeout: 1s
      retries: 10

  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    ports:
      - '8428:8428'
    command:
      - -storageDataPath=/vmsingle
      - -promscrape.config=/promscrape.yml
      - -loggerFormat=json
    volumes:
      - victorialogs-vector-docker-vm:/vmsingle
      - ./scrape.yml:/promscrape.yml
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8428/health"]
      interval: 1s
      timeout: 1s
      retries: 10

volumes:
  victorialogs-vector-docker-vl:
  victorialogs-vector-docker-vm:
