api:
  enabled: true
  address: 0.0.0.0:8686
sources:
  docker:
    type: docker_logs
  demo:
    type: demo_logs
    format: apache_common
    interval: 10
  vector_metrics:
    type: internal_metrics
transforms:
  msg_parser:
    type: remap
    inputs: [docker]
    source: |
      .log = parse_json!(.message)
      del(.message)
sinks:
  elasticsearch:
    type: elasticsearch
    inputs: [demo]
    endpoints: [http://victorialogs:9428/insert/elasticsearch/]
    mode: bulk
    api_version: v8
    compression: gzip
    healthcheck:
      enabled: false
    query:
      _msg_field: message
      _time_field: timestamp
      _stream_fields: source_type
    request:
      headers:
        AccountID: "0"
        ProjectID: "0"
  victoriametrics:
    type: prometheus_remote_write
    endpoint: http://victoriametrics:8428/api/v1/write
    inputs: [vector_metrics]
    healthcheck:
      enabled: false
