exporters:
  elasticsearch:
    endpoints:
      - http://victorialogs:9428/insert/elasticsearch
      - http://victorialogs-2:9428/insert/elasticsearch
receivers:
  filelog:
    include: [/var/lib/docker/containers/**/*.log]
    resource:
      region: us-east-1
service:
  telemetry:
    metrics:
      readers:
        - periodic:
            interval: 5000
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: http://victoriametrics:8428/opentelemetry/api/v1/push
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [elasticsearch]
