{
 "title": "VictoriaMetrics - Scrape Statistics",
 "tags": [ "victoriametrics" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "ds", "label": "DS", "query": "prometheus" },
   { "name": "agent", "label": "Agent" },
   { "name": "vmagent", "label": "VMAgent", "query": { "query": "label_values(up,vmagent)" } },
   { "name": "topk", "label": "Top", "query": "5,10,20,30" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(up,job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "The dashboard uses the parameters from [automatically generated metrics](https://docs.victoriametrics.com/victoriametrics/vmagent/#automatically-generated-metrics) and [cardinality limiter](https://docs.victoriametrics.com/victoriametrics/vmagent/#cardinality-limiter).\nTo display and sort data by different vmagent, you need to set the `vmagent` label and enable var `Agent`. To specify the label, use `-remoteWrite.label=vmagent=<label>` or `external_labels` in the parsing configuration\nCalculating metrics:\n- `Series Add` is calculated for the last `1h`. Thresholds: 2500, 5000\n- `Series` ceiling is taken from `scrape_series_limit`. Thresholds: 50%, 80%\n- `Dropped` is calculated over the last `24h`\n- `Size` ceiling is taken from `-promscrape.maxScrapeSize` as example. Thresholds: 8mb, 16mb\n- `Duration` ceiling is taken from `scrape_timeout_seconds`. Thresholds: 50%, 80%\n"
     }
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Job",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (job) (up{$agent} == 1)) / count(count by (job) (up{$agent}))",
     "legendFormat": "available"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (job) (up{$agent} == bool 1) > 0) or vector(0)",
     "legendFormat": "UP"
    },
    {
     "expr": "count(sum by (job) (up{$agent} == bool 0) > 0) or vector(0)",
     "legendFormat": "DOWN"
    }
   ]
  },
  {
   "title": "Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up == bool 1) / count(up)", "legendFormat": "available" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{$agent} == bool 1) or vector(0)",
     "legendFormat": "UP"
    },
    {
     "expr": "sum(up{$agent} == bool 0) or vector(0)",
     "legendFormat": "DOWN"
    }
   ]
  },
  {
   "title": "Series",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scrape_series_current{$agent})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Samples",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scrape_samples_scraped{$agent})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "table",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(up{job=~\"$job\", instance=~\"$instance\", $agent}) by (job,instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum_over_time(scrape_series_added{job=~\"$job\", instance=~\"$instance\", $agent}[1h])) by (job,instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_duration_seconds{job=~\"$job\", instance=~\"$instance\", $agent}) by (job,instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_samples_scraped{job=~\"$job\", instance=~\"$instance\", $agent}) by (job,instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_response_size_bytes{job=~\"$job\", instance=~\"$instance\", $agent}) by (job,instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_series_current{job=~\"$job\", instance=~\"$instance\", $agent}) by (job,instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_series_limit{job=~\"$job\", instance=~\"$instance\", $agent}) by (job,instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum_over_time(scrape_series_limit_samples_dropped{job=~\"$job\", instance=~\"$instance\", $agent}[24h])) by (job,instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_samples_scraped{job=~\"$job\", instance=~\"$instance\", $agent} - scrape_samples_post_metric_relabeling{job=~\"$job\", instance=~\"$instance\", $agent}) by (job,instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_timeout_seconds{job=~\"$job\", instance=~\"$instance\", $agent}) by (job,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coverage by job",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "sum(up{$agent} == bool 1) by (job) / count(up{$agent}) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Series",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top by series [1h]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk_max($topk, sum(sum_over_time(scrape_series_added{job=~\"$job\", instance=~\"$instance\", $agent}[1h])) by (job,instance))",
       "legendFormat": "{{job}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Top by series",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk_max($topk, sum(scrape_series_current{job=~\"$job\", instance=~\"$instance\", $agent}) by (job,instance))",
       "legendFormat": "{{job}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Top by relabeling",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk_max($topk, sum(scrape_samples_scraped{job=~\"$job\", instance=~\"$instance\", $agent} - scrape_samples_post_metric_relabeling{job=~\"$job\", instance=~\"$instance\", $agent}) by (job,instance))",
       "legendFormat": "{{job}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Top by dropped [24h]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk_max($topk, sum(sum_over_time(scrape_series_limit_samples_dropped{job=~\"$job\", instance=~\"$instance\", $agent}[24h])) by (job,instance))",
       "legendFormat": "{{job}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Top by size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk_max($topk, sum(scrape_response_size_bytes{job=~\"$job\", instance=~\"$instance\", $agent}) by (job,instance))",
       "legendFormat": "{{job}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Top by duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk_max($topk, sum(scrape_duration_seconds{job=~\"$job\", instance=~\"$instance\", $agent}) by (job,instance))",
       "legendFormat": "{{job}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Top by samples",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk_max($topk, sum(scrape_samples_scraped{job=~\"$job\", instance=~\"$instance\", $agent}) by (job,instance))",
       "legendFormat": "{{job}}/{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}