{
 "title": "VictoriaMetrics - Select",
 "tags": [
  "victoriametrics",
  "vmselect"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(vm_app_version{instance=~\".*vmselect.*\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Selecters",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vm_app_version{version=~\"^vmselect.*\"})"
    }
   ]
  },
  {
   "title": "Listeners",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_tcplistener_conns{instance=~\".*$host.*\"})"
    }
   ]
  },
  {
   "title": "Storage connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_tcpdialer_conns{instance=~\".*$host.*\"})"
    }
   ]
  },
  {
   "title": "Rows read",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(vm_metric_rows_read_total{instance=~\".*$host.*\"})"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(vm_http_requests_all_total{instance=~\".*$host.*\"})"
    }
   ]
  },
  {
   "title": "Received",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_tcplistener_read_bytes_total{instance=~\".*$host.*\"})"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_tcpdialer_written_bytes_total{instance=~\".*$host.*\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "vm_app_uptime_seconds{instance=~\".*$host.*\"}",
     "legendFormat": "Seconds"
    }
   ]
  },
  {
   "title": "HTTP request duration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "vm_http_request_duration_seconds{instance=~\".*$host.*\"}",
     "legendFormat": "{{ quantile}} quantile ({{ path }})"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_cache_entries{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Entries"
    },
    {
     "expr": "sum(rate(vm_cache_misses_total{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Misses"
    },
    {
     "expr": "sum(rate(vm_cache_requests_total{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Memory heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\".*$host.*\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=~\".*$host.*\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\".*$host.*\"}",
     "legendFormat": "In used"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{instance=~\".*$host.*\"}",
     "legendFormat": "System"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 } },
  {
   "title": "TCP dialer errors/sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_tcpdialer_errors_total{instance=~\".*$host.*\",type=\"dial\"}[2m]))",
     "legendFormat": "Dial"
    },
    {
     "expr": "sum(rate(vm_tcpdialer_errors_total{instance=~\".*$host.*\",type=\"close\"}[2m]))",
     "legendFormat": "Close"
    },
    {
     "expr": "sum(rate(vm_tcpdialer_errors_total{instance=~\".*$host.*\",type=\"write\"}[2m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(vm_tcpdialer_errors_total{instance=~\".*$host.*\",type=\"read\"}[2m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "TCP dialer errors/sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_tcplistener_errors_total{instance=~\".*$host.*\",type=\"accept\"}[2m]))",
     "legendFormat": "Accept"
    },
    {
     "expr": "sum(rate(vm_tcplistener_errors_total{instance=~\".*$host.*\",type=\"close\"}[2m]))",
     "legendFormat": "Close"
    },
    {
     "expr": "sum(rate(vm_tcplistener_errors_total{instance=~\".*$host.*\",type=\"write\"}[2m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(vm_tcplistener_errors_total{instance=~\".*$host.*\",type=\"read\"}[2m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "TCP dialer RW bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_tcpdialer_written_bytes_total{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(vm_tcpdialer_read_bytes_total{instance=~\".*$host.*\"}[2m])) * -1",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "TCP listener RW bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_tcplistener_written_bytes_total{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(vm_tcplistener_read_bytes_total{instance=~\".*$host.*\"}[2m])) * -1",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "TCP dialer RW",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_tcpdialer_write_calls_total{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Write calls"
    },
    {
     "expr": "sum(rate(vm_tcpdialer_write_timeouts_total{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Write timeouts"
    },
    {
     "expr": "sum(rate(vm_tcpdialer_read_calls_total{instance=~\".*$host.*\"}[2m])) * -1",
     "legendFormat": "Read calls"
    },
    {
     "expr": "sum(rate(vm_tcpdialer_read_timeouts_total{instance=~\".*$host.*\"}[2m])) * -1",
     "legendFormat": "Read timeouts"
    }
   ]
  },
  {
   "title": "TCP listener RW",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_tcplistener_write_calls_total{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Write calls"
    },
    {
     "expr": "sum(rate(vm_tcplistener_write_timeouts_total{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Write timeouts"
    },
    {
     "expr": "sum(rate(vm_tcplistener_read_calls_total{instance=~\".*$host.*\"}[2m])) * -1",
     "legendFormat": "Read calls"
    },
    {
     "expr": "sum(rate(vm_tcplistener_read_timeouts_total{instance=~\".*$host.*\"}[2m])) * -1",
     "legendFormat": "Read timeouts"
    }
   ]
  }
 ]
}