{
 "title": "VictoriaMetrics - Storage",
 "tags": [
  "victoriametrics",
  "vmstorage"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(vm_app_version{instance=~\".*vmstorage.*\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Storages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vm_app_version{version=~\"^vmstorage.*\"})"
    }
   ]
  },
  {
   "title": "Listeners",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_tcplistener_conns{instance=~\".*$host.*\"})"
    }
   ]
  },
  {
   "title": "Data size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(vm_data_size_bytes{instance=~\".*$host.*\"})"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_cache_size_bytes{instance=~\".*$host.*\"})"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(vm_http_requests_all_total{instance=~\".*$host.*\"})"
    }
   ]
  },
  {
   "title": "Received",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_tcplistener_read_bytes_total{instance=~\".*$host.*\"})"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_tcplistener_written_bytes_total{instance=~\".*$host.*\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "vm_app_uptime_seconds{instance=~\".*$host.*\"}",
     "legendFormat": "Seconds"
    }
   ]
  },
  {
   "title": "Parts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_parts{instance=~\".*$host.*\"})"
    }
   ]
  },
  {
   "title": "Merges",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_merges_total{instance=~\".*$host.*\"})"
    }
   ]
  },
  {
   "title": "Rows",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_rows{instance=~\".*$host.*\",type!=\"indexdb\"})"
    }
   ]
  },
  {
   "title": "Metrics inserted",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_vminsert_metrics_read_total{instance=~\".*$host.*\"})"
    }
   ]
  },
  {
   "title": "Metrics selected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_vmselect_metric_rows_read_total{instance=~\".*$host.*\"})"
    }
   ]
  },
  {
   "title": "Metrics deleted",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_vmselect_delete_metrics_requests_total{instance=~\".*$host.*\"})"
    }
   ]
  },
  {
   "title": "HTTP request duration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "vm_http_request_duration_seconds{instance=~\".*$host.*\"}",
     "legendFormat": "{{ quantile}} quantile ({{ path }})"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vm_cache_entries{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Entries"
    },
    {
     "expr": "sum(irate(vm_cache_misses_total{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Misses"
    },
    {
     "expr": "sum(irate(vm_cache_requests_total{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vm_cache_size_bytes{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Cache"
    },
    {
     "expr": "sum(irate(vm_data_size_bytes{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Data"
    }
   ]
  },
  {
   "title": "Rows",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vm_rows{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(irate(vm_rows_merged_total{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Merged"
    },
    {
     "expr": "sum(irate(vm_rows_deleted_total{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Deleted"
    },
    {
     "expr": "sum(irate(vm_pending_rows{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "TCP listener errors/sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vm_tcplistener_errors_total{instance=~\".*$host.*\",type=\"accept\"}[2m]))",
     "legendFormat": "Accept"
    },
    {
     "expr": "sum(irate(vm_tcplistener_errors_total{instance=~\".*$host.*\",type=\"close\"}[2m]))",
     "legendFormat": "Close"
    },
    {
     "expr": "sum(irate(vm_tcplistener_errors_total{instance=~\".*$host.*\",type=\"write\"}[2m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(vm_tcplistener_errors_total{instance=~\".*$host.*\",type=\"read\"}[2m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Memory heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\".*$host.*\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=~\".*$host.*\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\".*$host.*\"}",
     "legendFormat": "In used"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{instance=~\".*$host.*\"}",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "TCP listener RW bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vm_tcplistener_written_bytes_total{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(vm_tcplistener_read_bytes_total{instance=~\".*$host.*\"}[2m])) * -1",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "TCP listener RW",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vm_tcplistener_write_calls_total{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Write calls"
    },
    {
     "expr": "sum(irate(vm_tcplistener_write_timeouts_total{instance=~\".*$host.*\"}[2m]))",
     "legendFormat": "Write timeouts"
    },
    {
     "expr": "sum(irate(vm_tcplistener_read_calls_total{instance=~\".*$host.*\"}[2m])) * -1",
     "legendFormat": "Read calls"
    },
    {
     "expr": "sum(irate(vm_tcplistener_read_timeouts_total{instance=~\".*$host.*\"}[2m])) * -1",
     "legendFormat": "Read timeouts"
    }
   ]
  }
 ]
}