{
 "title": "VictoriaLogs docker compose overview",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total rows",
   "type": "stat",
   "description": "How many rows are in storage",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(vl_rows)" }
   ]
  },
  {
   "title": "Ingestion rate",
   "type": "stat",
   "description": "Shows the datapoints ingestion rate.",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vl_rows_ingested_total))"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "stat",
   "description": "Total amount of used disk space",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vl_compressed_data_size_bytes)"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Ingestred data points total",
   "type": "timeseries",
   "description": "How many datapoints are inserted into storage in total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "vl_rows_ingested_total", "legendFormat": "victorialogs" },
    {
     "expr": "filebeat_libbeat_output_events{type=\"acked\"}",
     "legendFormat": "filebeat"
    }
   ]
  },
  {
   "title": "Datapoints ingestion rate ",
   "type": "timeseries",
   "description": "How many datapoints are inserted into storage per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vl_rows_ingested_total))",
     "legendFormat": "victorialogs ingestion rate"
    }
   ]
  },
  {
   "title": "Requests rate ",
   "type": "timeseries",
   "description": "* `*` - unsupported query path\n* `/insert` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - read the data",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vl_http_requests_total)) by (path) > 0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Disk space usage ",
   "type": "timeseries",
   "description": "Shows the amount of on-disk space occupied by data before and after compressiom",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(vl_compressed_data_size_bytes)",
     "legendFormat": "compressed data size"
    },
    {
     "expr": "sum(vl_uncompressed_data_size_bytes)",
     "legendFormat": "uncompressed data size"
    }
   ]
  },
  {
   "title": "Data compression ratio",
   "type": "timeseries",
   "description": "Compression ratio for the data on a disk. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " sum(vl_uncompressed_data_size_bytes) / sum(vl_compressed_data_size_bytes)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}