// vmalertSourceParam routes the request to a single vmalert from -vmalert.proxyURL.
// An empty source means that the request is sent to all the configured vmalerts.
//
// This is the arg understood by vmselect. vmui links carry the owning vmalert
// in GROUP_SOURCE_PARAM instead - see components/ExploreAlerts/helpers.ts.
const vmalertSourceParam = (source: string): string =>
  source ? `&vmalert_source=${encodeURIComponent(source)}` : "";

export const getGroupsUrl = (server: string, search: string, type: string, states: string[], maxGroups: number, source: string): string => {
  return `${server}/vmalert/api/v1/rules?datasource_type=prometheus&search=${encodeURIComponent(search)}&type=${encodeURIComponent(type)}&state=${states.map(encodeURIComponent).join(",")}&group_limit=${maxGroups}&extended_states=true${vmalertSourceParam(source)}`;
};

// Entity IDs are generated by every vmalert independently, so the requested entity
// is owned by a single vmalert. Passing its source avoids fanning the request out
// to the vmalerts, which do not own the entity and respond with an error.
export const getItemUrl = (
  server: string,
  groupId: string,
  id: string,
  mode: string,
  source: string,
): string => {
  return `${server}/vmalert/api/v1/${mode}?group_id=${groupId}&${mode}_id=${id}${vmalertSourceParam(source)}`;
};

export const getGroupUrl = (
  server: string,
  id: string,
  source: string,
): string => {
  return `${server}/vmalert/api/v1/group?group_id=${id}${vmalertSourceParam(source)}`;
};

export const getNotifiersUrl = (server: string, source: string): string => {
  const url = `${server}/vmalert/api/v1/notifiers`;
  // vmalertSourceParam() isn't used here, since this is the first query arg in the URL.
  return source ? `${url}?vmalert_source=${encodeURIComponent(source)}` : url;
};

// parseJsonResponse parses the response body as JSON.
//
// It throws an error describing the actual response instead of an opaque
// "Unexpected end of JSON input" SyntaxError when the body is empty or isn't JSON.
// This happens when a proxy in front of vmalert replies with a plain error page.
export const parseJsonResponse = async (response: Response) => {
  const text = await response.text();
  try {
    return JSON.parse(text);
  } catch {
    const details = text.trim() || "empty response";
    throw new Error(`${response.status} ${response.statusText}: ${details.slice(0, 512)}`);
  }
};
