apiVersion: 1

datasources:
  - name: VictoriaLogs
    type: victoriametrics-logs-datasource
    access: proxy
    url:  http://vmauth:8427/

  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://vmauth:8427/
