FROM node:20-alpine3.19

RUN apk update && \
    apk upgrade && \
    apk add --no-cache bash bash-doc bash-completion libtool autoconf automake nasm pkgconfig libpng gcc make g++ zlib-dev gawk && \
    mkdir -p /app

WORKDIR /app
