server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://victorialogs:9428/insert/loki/api/v1/push?_stream_fields=instance,job,host,app
    tenant_id: "0:0"

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:5140
    relabel_configs:
      - source_labels: [ '__syslog_message_hostname' ]
        target_label: 'host'
      - source_labels: [ '__syslog_message_app_name' ]
        target_label: 'app'
      - source_labels: [ '__syslog_message_proc_id' ]
        target_label: 'pid'


  - job_name: containers
    pipeline_stages:
      - docker: { }
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
