{
 "title": "Elastic vs VLogs - stats only",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "containers_selector", "query": ".*(vlogs|elastic).*" },
   {
    "name": "containers",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{name!=\"\",}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"$containers\"}[5m])) by (name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\"$containers\"}[5m]) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk space used",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_disk_usage_bytes{path=~\"$containers_selector\"}[5m]) by (path)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}