// Package vmalertapi contains response types of the vmalert alerting API.
//
// The types are shared between vmalert, which generates the responses,
// and lib/vmalertproxy, which merges responses from multiple vmalerts.
// Keeping them in a single place guarantees that the merged response stays
// in sync with the response generated by vmalert.
//
// This package intentionally contains type definitions only and has no imports,
// so importing it never pulls in anything else.
//
// Every response is generic over the type of the returned entity, since vmalert
// builds responses from typed entities such as rule.ApiGroup, while lib/vmalertproxy
// merges responses without the need to know the entity internals - it uses
// json.RawMessage as the entity type.
package vmalertapi

// StatusSuccess is the value of the `status` field at a successful response.
const StatusSuccess = "success"

// StatusError is the value of the `status` field at a failed response.
const StatusError = "error"

// ListGroupsResponse is the response to /api/v1/rules
type ListGroupsResponse[Group any] struct {
	Status      string `json:"status"`
	Page        int    `json:"page,omitempty"`
	TotalPages  int    `json:"total_pages,omitempty"`
	TotalGroups int    `json:"total_groups,omitempty"`
	TotalRules  int    `json:"total_rules,omitempty"`
	Data        struct {
		Groups []Group `json:"groups"`
	} `json:"data"`

	// Warnings is set by lib/vmalertproxy when some of the -vmalert.proxyURL are unavailable.
	// vmalert itself never sets it.
	Warnings []string `json:"warnings,omitempty"`
}

// ListAlertsResponse is the response to /api/v1/alerts
type ListAlertsResponse[Alert any] struct {
	Status string `json:"status"`
	Data   struct {
		Alerts []Alert `json:"alerts"`
	} `json:"data"`

	// Warnings is set by lib/vmalertproxy when some of the -vmalert.proxyURL are unavailable.
	// vmalert itself never sets it.
	Warnings []string `json:"warnings,omitempty"`
}

// ListNotifiersResponse is the response to /api/v1/notifiers
type ListNotifiersResponse[Notifier any] struct {
	Status string `json:"status"`
	Data   struct {
		Notifiers []Notifier `json:"notifiers"`
	} `json:"data"`

	// Warnings is set by lib/vmalertproxy when some of the -vmalert.proxyURL are unavailable.
	// vmalert itself never sets it.
	Warnings []string `json:"warnings,omitempty"`
}
