title: VictoriaMetrics
author: VictoriaMetrics
email: info@victoriametrics.com
description: >
  The High Performance Open Source Time Series Database & Monitoring Solution

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

google:
  gtag: G-N9SVT8S3HK

plugins:
  - github-pages


