{
 "title": "Vmanomaly Guide",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mode",
    "label": "Mode",
    "query": {
     "query": "label_values(node_cpu_seconds_total,mode)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 0 },
   "options": {
    "content": "If you don't observe any data initially, please wait a few minutes for it to appear. \n\nUpon the first running the guide (if there is not enough node_exporter monitoring data collected in your system), you may notice a significant number of false positive anomalies found. The predictions will become more accurate with at least two weeks' (full `fit_window`) worth of data provided to vmanomaly.\n\nEach row displays information for a distinct mode. The query used for anomaly detection is `sum(rate(node_cpu_seconds_total[5m])) by (mode, instance, job)`.\n"
   }
  },
  { "title": "CPU Mode:  $mode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "mode" },
  {
   "title": "CPU rate sum for $mode mode",
   "type": "timeseries",
   "description": "sum(rate(node_cpu_seconds_total{mode=~\"$mode\"}[5m])) by (mode, instance,job)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=~\"$mode\"}[5m])) by (mode, instance,job)",
     "legendFormat": "Instance: {{instance}}, Job {{job}}"
    }
   ]
  },
  {
   "title": "Anomaly Scores for $mode mode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "anomaly_score{mode=~\"$mode\"}",
     "legendFormat": "Instance: {{instance}}, Job: {{job}}"
    },
    { "expr": "vector(1)", "legendFormat": "threshold" }
   ]
  },
  {
   "title": "Predicted Value and Boundaries for $mode mode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "yhat{mode=~\"$mode\"}",
     "legendFormat": "Predicted Value: yhat"
    },
    {
     "expr": "yhat_lower{mode=~\"$mode\"}",
     "legendFormat": "Predicted Lower Boundary"
    },
    {
     "expr": "yhat_upper{mode=~\"$mode\"}",
     "legendFormat": "Predicted Upper Boundary"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=~\"$mode\"}[5m])) by (mode, instance,job)",
     "legendFormat": "Value"
    }
   ]
  }
 ]
}