services:
  vector:
    image: docker.io/timberio/vector:0.40.1-distroless-static
    restart: on-failure
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
      - ./vector.yaml:/etc/vector/vector.yaml:ro
    user: root
    ports:
      - '8686:8686'
    depends_on: [victorialogs-1,victorialogs-2]

  victorialogs-1:
    image: docker.io/victoriametrics/victoria-logs:v0.29.0-victorialogs
    volumes:
      - victorialogs-vector-docker-vl-ha-single-1:/vlogs
    command:
      - -storageDataPath=/vlogs
      - -loggerFormat=json
  victorialogs-2:
    image: docker.io/victoriametrics/victoria-logs:v0.29.0-victorialogs
    volumes:
      - victorialogs-vector-docker-vl-ha-single-2:/vlogs
    command:
      - -storageDataPath=/vlogs
      - -loggerFormat=json
  vmauth:
    container_name: vmauth
    image: victoriametrics/vmauth:v1.103.0
    depends_on:
      - "victorialogs-1"
      - "victorialogs-2"
    volumes:
      - ./auth.yml:/etc/auth.yml
    command:
      - '--auth.config=/etc/auth.yml'
    ports:
      - 8427:8427
    restart: always

volumes:
  victorialogs-vector-docker-vl-ha-single-1:
  victorialogs-vector-docker-vl-ha-single-2:
