api:
  enabled: true
  address: 0.0.0.0:8686
sources:
  docker:
    type: docker_logs
transforms:
  msg_parser:
    type: remap
    inputs:
      - docker
    source: |
      if exists(.message) {
        .log, err = parse_json(.message)
        if err == null {
          del(.message)
        }
      }
sinks:
  console_out:
    type: console
    inputs:
      - msg_parser
    encoding:
      codec: json
  vlogs_http_1:
    type: http
    inputs:
      - msg_parser
    uri: http://victorialogs-1:9428/insert/jsonline?_stream_fields=source_type,host,container_name&_msg_field=log.msg&_time_field=timestamp
    encoding:
      codec: json
    framing:
      method: newline_delimited
    compression: gzip
    healthcheck:
      enabled: false
    request:
      headers:
        AccountID: '0'
        ProjectID: '0'
  vlogs_http_2:
    type: http
    inputs:
      - msg_parser
    uri: http://victorialogs-2:9428/insert/jsonline?_stream_fields=source_type,host,container_name&_msg_field=log.msg&_time_field=timestamp
    encoding:
      codec: json
    framing:
      method: newline_delimited
    compression: gzip
    healthcheck:
      enabled: false
    request:
      headers:
        AccountID: '0'
        ProjectID: '0'

