exporters:
  otlphttp:
    logs_endpoint: http://victorialogs:9428/insert/opentelemetry/v1/logs
  debug:
    verbosity: detailed
receivers:
  filelog:
    include: [/var/lib/docker/containers/**/*.log]
    resource:
      region: us-east-1
service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [otlphttp, debug]
