services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.1
    user: root
    volumes:
      - ./pipeline.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on: [victorialogs-1,victorialogs-2]
    ports:
      - "5140:5140"

  victorialogs-1:
    image: docker.io/victoriametrics/victoria-logs:v0.29.0-victorialogs
    volumes:
      - victorialogs-logstash-vl-ha-single-1:/vlogs
    command:
      - -storageDataPath=/vlogs
  victorialogs-2:
    image: docker.io/victoriametrics/victoria-logs:v0.29.0-victorialogs
    volumes:
      - victorialogs-logstash-vl-ha-single-2:/vlogs
    command:
      - -storageDataPath=/vlogs
  vmauth:
    container_name: vmauth
    image: victoriametrics/vmauth:v1.103.0
    depends_on:
      - "victorialogs-1"
      - "victorialogs-2"
    volumes:
      - ./auth.yml:/etc/auth.yml
    command:
      - '--auth.config=/etc/auth.yml'
    ports:
      - 8427:8427
    restart: always

volumes:
  victorialogs-logstash-vl-ha-single-1:
  victorialogs-logstash-vl-ha-single-2:
