// Code generated by qtc from "labels_response.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// LabelsResponse generates response for /api/v1/labels .See https://prometheus.io/docs/prometheus/latest/querying/api/#getting-label-names

//line app/vmselect/prometheus/labels_response.qtpl:4
package prometheus

//line app/vmselect/prometheus/labels_response.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line app/vmselect/prometheus/labels_response.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line app/vmselect/prometheus/labels_response.qtpl:4
func StreamLabelsResponse(qw422016 *qt422016.Writer, labels []string) {
//line app/vmselect/prometheus/labels_response.qtpl:4
	qw422016.N().S(`{"status":"success","data":[`)
//line app/vmselect/prometheus/labels_response.qtpl:8
	for i, label := range labels {
//line app/vmselect/prometheus/labels_response.qtpl:9
		qw422016.N().Q(label)
//line app/vmselect/prometheus/labels_response.qtpl:10
		if i+1 < len(labels) {
//line app/vmselect/prometheus/labels_response.qtpl:10
			qw422016.N().S(`,`)
//line app/vmselect/prometheus/labels_response.qtpl:10
		}
//line app/vmselect/prometheus/labels_response.qtpl:11
	}
//line app/vmselect/prometheus/labels_response.qtpl:11
	qw422016.N().S(`]}`)
//line app/vmselect/prometheus/labels_response.qtpl:14
}

//line app/vmselect/prometheus/labels_response.qtpl:14
func WriteLabelsResponse(qq422016 qtio422016.Writer, labels []string) {
//line app/vmselect/prometheus/labels_response.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vmselect/prometheus/labels_response.qtpl:14
	StreamLabelsResponse(qw422016, labels)
//line app/vmselect/prometheus/labels_response.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line app/vmselect/prometheus/labels_response.qtpl:14
}

//line app/vmselect/prometheus/labels_response.qtpl:14
func LabelsResponse(labels []string) string {
//line app/vmselect/prometheus/labels_response.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vmselect/prometheus/labels_response.qtpl:14
	WriteLabelsResponse(qb422016, labels)
//line app/vmselect/prometheus/labels_response.qtpl:14
	qs422016 := string(qb422016.B)
//line app/vmselect/prometheus/labels_response.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vmselect/prometheus/labels_response.qtpl:14
	return qs422016
//line app/vmselect/prometheus/labels_response.qtpl:14
}
