name: Package tests

on:
  push:
    branches:
      - cluster
      - master
    paths:
      - '.github/workflows/test_package.yml'
      - '**/Dockerfile*'
      - '**/Makefile'
  pull_request:
    branches:
      - cluster
      - master
    paths:
      - '.github/workflows/test_package.yml'
      - '**/Dockerfile*'
      - '**/Makefile'

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  test_release:
    name: Test Release
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Go
        id: go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false

      - name: Cache Go artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/bin
            ~/go/pkg/mod
          key: go-artifacts-${{ runner.os }}-test-release-${{ steps.go.outputs.go-version }}-${{ hashFiles('Makefile', '**/Dockerfile*', '**/Makefile') }}
          restore-keys: go-artifacts-${{ runner.os }}-test-release-

      - name: Run make release
        run: |
          make clean
          make release

      - name: Run release tests
        run: make test-release-victoria-metrics
