scrape_configs:
  - job_name: "victoriametrics"
    scrape_interval: 30s
    static_configs:
      - targets:
          - victoriametrics:8428
  - job_name: "victorialogs"
    scrape_interval: 30s
    static_configs:
      - targets:
          - victorialogs:9428